### ISSUE TITLE
Orphan stake explanation

### ISSUE THREAD

**Issue by colvano** [NAVCoin/navcoin-core#105]
Behind an orphan stake create a "?" button. When clicked on by the user it will show a small popup explaining it is an orphan stake.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-25T01:51:33+13:00","ped":"2017-11-25T05:23:19+13:00"})

**Comment by red010b37** [comment]
This is has been addressed with this PR, that has been into master. :)

https://github.com/NAVCoin/navcoin-core/pull/221
