### ISSUE TITLE
hash mismatch for navcoin-4.0.6-x86_64-linux-gnu.tar.gz - urgent!

### ISSUE THREAD

**Issue by 2SI3NX** [NAVCoin/navcoin-core#107]
Am i the only one getting a wrong hash match according to your github release page??
Has navcoin-4.0.6-x86_64-linux-gnu.tar.gz  been compromised?

im getting `af39e3fa2f8ff49fe4a01e979a841f5bb787bf027fe977104afc6b3e86117d2b`

which doesnt match `8362afa25a989a1fceac08630823360c2a77c07f7384ed9220ff0cefb58b84d7`

**Comment by 2SI3NX** [comment]
I just noticed now on your site: https://navcoin.org/advanced-downloads/
that my hash matches the site's, however does not match your github release's page. Please explain why theres a different hash on your github release page.

**Comment by aguycalled** [comment]
fixed git release with correct hash
