### ISSUE TITLE
NavCoin Wallet executes Ripple Ledger Wallet

### ISSUE THREAD

**Issue by hauweg** [NAVCoin/navcoin-core#109]
hallo, 

i downloaded the navcoin core wallet from navcoin homepage. after extraction i started the app with the file navcoin-cli. but instead of opening the navcoin wallet, it opens the ripple ledger wallet, which is also installed on my system (latest linux xubunt)

thanks in advance for your advices!!! :)

**Comment by aguycalled** [comment]
Looks like something is wrong on your system. I'd still verify that your download hash matches the one specified on the website.

For further support, please just Discord, Navcoin.org forum or Reddit.
