### ISSUE TITLE
missing lib/libcurl.4.dylib in mac os x distribution

### ISSUE THREAD

**Issue by brianium** [NAVCoin/navcoin-core#121]
I am attempting to use `navcoin-cli` provided by `navcoin-4.1.2-osx64.tar.gz` for testing purposes - and I get the following error when attempting to execute it:

```
dyld: Library not loaded: /home/ubuntu/build/navcoin-core/depends/x86_64-apple-darwin11/lib/libcurl.4.dylib
  Referenced from: /Users/brian/Downloads/navcoin-4.1.2/bin/./navcoin-cli
  Reason: Incompatible library version: navcoin-cli requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0
Abort trap: 6
```

Any help would be appreciated.

Thank you :)

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-25T05:34:17+13:00","ped":"2018-01-26T01:34:17+13:00"})

┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;NAVCoin&#x2F;navcoin-core&#x2F;commit&#x2F;007c4beb0ea4af940d517d90af3fef4001c96c0d">compat: #121 missing lib in osx</a>

**Comment by aguycalled** [comment]
what os version are you using?

**Comment by brianium** [comment]
macOS High Sierra
Version 10.13.2 (17C88)

**Comment by aguycalled** [comment]
if you are using the headless version of the node, please use brew to install curl and any other dependencies your system may need.

**Comment by brianium** [comment]
Hmmmm... I tried brew installing `curl` before posting the issue, and I still receive the error.

**Comment by ro-savage** [comment]
Have exactly the same issue.

My commandline curl is up to date, I am not sure where it's trying to reference / look for curl.

**Comment by aguycalled** [comment]
Solved, pending pr
