### ISSUE TITLE
Community Fund Documententation - Incorrect URL Path Identified

### ISSUE THREAD

**Issue by x-Tsunami-x** [NAVCoin/navcoin-core#122]
Typo mistake in navcoin-cfund-beta.pdf that needs addressing

Under Requirements in your documentation it lists:
http://build.nav.community/v4.1.2.

In fact the correct path is
https://build.nav.community/v4.1.2

**Comment by aguycalled** [comment]
http:// redirects to https://

**Comment by x-Tsunami-x** [comment]
I received an error in Edge

**Comment by x-Tsunami-x** [comment]
working now
