### ISSUE TITLE
Navcoin wallet not work with openssl 1.1 on Linux

### ISSUE THREAD

**Issue by ata** [NAVCoin/navcoin-core#131]
Currently I'm using GNU/Linux Debian 9, witch is the latest Debian stable.
Debian is mother of many distro.Which is make package/library that use in debian, probably will use in other disto as well, including Ubuntu. 
It maen, if Navcoin can run perfectly on Debian, it will mostly run with other distro as well.
As far I know, Navcoin depend on openssl1.0, which is not available in Debian Stable. 

Can be next linux build using openssl1.1 instead of openssl1.0?

**Comment by aguycalled** [comment]
Please, keep discussion around this on #68
