### ISSUE TITLE
Check consistency of CFund DB

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/navcoin-core#137]
If the CFund DB is removed or corrupted there'll be incongruences on the state of the proposals and differences in the consensus between nodes.

CFund DB should be rebuilt in case it is not synced up to tip of the chain.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-01-29T09:00:00+13:00","ped":"2018-02-02T18:00:00+13:00"})

┆Attachments: <a href="https:&#x2F;&#x2F;github.com&#x2F;NAVCoin&#x2F;navcoin-core&#x2F;commit&#x2F;5f78ada99277157cfaec0a640c690cf5961f89c2">cfund: check db consistency on init</a> | <a href="https:&#x2F;&#x2F;github.com&#x2F;NAVCoin&#x2F;navcoin-core&#x2F;pull&#x2F;151">navcoin-core #151 V4.1.2 cfund check db</a>

**Comment by navtrello** [comment]
➤ alex v commented:

waiting for the existing pull requests to be closed before opening a new one
