### ISSUE TITLE
Investigate & Review Difficulty & Blocktime

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/navcoin-core#141]
Collaborate with Alex on reviewing the staking difficulty bug & block time inaccuracy

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by aguycalled** [comment]
Related to some incongruence between GetAdjustedTime() and GetPastTimeLimit()

**Comment by red010b37** [comment]
This was resolved with the ntp sync fix in the 4.2.0 release: Please see here:
https://github.com/NAVCoin/navcoin-core/blob/master/doc/release-notes/release-notes-4.2.0.md
