### ISSUE TITLE
Investigating options for keeping NavCoinCore up to date with Bitcoin

### ISSUE THREAD

**Issue by navtrello** [NAVCoin/navcoin-core#142]
Current best idea of approach:

The daemon should largely be what Bitcoin Core puts out and we kept clean and updateable. Any changes to the daemon should be kept seperate and implemented as overrides to the Bitcoin Core source. Investigation on how to do this is required, class extends etc.. or more like a seperate middleware?

Investigate how litecoin keeps up to date with bitcoin core. And how they implement BIPs before bitcoin and see if its something we can replicate.

After investigation compile the latest bitcoin core and do some feasibility experiments to solidify the plan of how we extend / inject our functionality.

The intention here is to be in a similar position to NavPay where the core libraries are keep up to date with the big players but we have our own custom front end that uses html/js/css as an electron application.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":false,"ownerId":false,"dependencies":[]})

**Comment by red010b37** [comment]
This has come to a conclusion that keeping the core in sync with bitcoin is not possible with the current implementation
