### ISSUE TITLE
Compiling Issue with Ubuntu.

### ISSUE THREAD

**Issue by schultzynj** [NAVCoin/navcoin-core#144]
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1067:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was bui
    ^
Makefile:8149: recipe for target 'qt/qt_navcoin_qt-navcoin.o' failed
make[2]: *** [qt/qt_navcoin_qt-navcoin.o] Error 1
make[2]: Leaving directory '/root/NAV/src'
Makefile:9155: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/root/NAV/src'
Makefile:683: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-02-05T09:00:00+13:00","ped":"2018-02-09T18:00:00+13:00"})

**Comment by red010b37** [comment]
You will need to build the depends Dir your self.

After you have installed everything.  Run the following set of commands to clone the repo and build all  the app.

`git clone https://github.com/NAVCoin/navcoin-core
cd navcoin-core/depends
make
cd ..
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu 
make`

**Comment by schultzynj** [comment]
Thanks for that :)

**Comment by red010b37** [comment]
Np :)
