### ISSUE TITLE
GUI: libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/navcoin-core#190]
https://stackoverflow.com/a/36554876

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2018-04-16T09:00:00+12:00","ped":"2018-04-20T18:00:00+12:00"})

**Comment by marcus290** [comment]
Closed via #419
