### ISSUE TITLE
Add a link to info.navcoin.org to the toolbar

### ISSUE THREAD

**Issue by matt-auckland** [navcoin/navcoin-core#196]
Currently when users look for help inside the wallet there isn't anything of use or any indication of where to go to find information.

**Comment by aguycalled** [comment]
bounty assigned to @mxaddict, pending merge

**Comment by mxaddict** [comment]
@aguycalled NRXfZ1egFxMSUsc4Ufpi4Lm7DdXStYmeBG

**Comment by aguycalled** [comment]
Paid b85013dde891d61484dc1f94833b5781316f3f3e896d031ca121b5930f02ad0f

**Comment by mxaddict** [comment]
Closing issue since PR has been merged
