### ISSUE TITLE
Gui not running on *buntu 18.04 LTS

### ISSUE THREAD

**Issue by n00by1** [NAVCoin/navcoin-core#204]
After upgrading to 18.04 LTS (Kubuntu) i get this output launching navcoin-qt.``./navcoin-qt
./navcoin-qt: symbol lookup error: ./navcoin-qt: undefined symbol: SSLeay`` 

Also trying to run navcoin-cli `./navcoin-cli: symbol lookup error: ./navcoin-cli: undefined symbol: CRYPTO_set_locking_callback`

**Comment by aguycalled** [comment]
could you try v4.1.2?

binaries available at http://build.nav.community/v4.1.2

**Comment by n00by1** [comment]
Yes, it works. Thanks again!
