### ISSUE TITLE
4.2 No release for arm devices - NavPi stakebox

### ISSUE THREAD

**Issue by vergotle** [NAVCoin/navcoin-core#220]
Hi

Auto update fails on NavPi stakebox with a 404 HTTP error.  This causes a NavPi stakebox to crash and a reboot is necessary to bring the NavPi stake box back online.

will there be a release for arm devices?

**Comment by craigmacgregor** [comment]
We had to pull the ARM release due to an error we found on the NavPi. Please see this post:

https://navcoin.org/notices/2018-06-06-navcoin-4-2-0-navpi-patch-notice/

**Comment by aguycalled** [comment]
4.2.1 is already out, closing this issue
