### ISSUE TITLE
Display issue on Lenovo Yoga 920 low-res

### ISSUE THREAD

**Issue by IfaqYurmama** [navcoin/navcoin-core#223]
Lenovo Yoga 920

![grafik](https://user-images.githubusercontent.com/33290035/41317177-bbf37d04-6e94-11e8-94b0-757efe153b6d.png)

--- Not my own issue, taken from [reddit](https://www.reddit.com/r/NavCoin/comments/8qj3sc/navcoin_wallet_v421_home_screen_looks_off_on_my/)  ---

**Comment by skillnwits** [comment]
The older wallet version did not have that issue. The resolution on my Lenovo Yoga 920 laptop is 3840X2160.

**Comment by IfaqYurmama** [comment]
From the screenshot it looks like you're using scale-up. What percentage is
that set at?

**Comment by skillnwits** [comment]
I'm using 300%, but the previous wallet version did NOT require me to change my display settings.
![display](https://user-images.githubusercontent.com/40217613/41348396-154fb1dc-6ed2-11e8-8811-701adcbd5038.PNG)

**Comment by red010b37** [comment]
Thanks for the info we will take a look

**Comment by aguycalled** [comment]
@IfaqYurmama does 4.5.0 solve this?

**Comment by IfaqYurmama** [comment]
@aguycalled I only opened it for a guy on reddit who since deleted his account. Maybe @skillnwits can confirm.

**Comment by skillnwits** [comment]
Im on vacation and will get back on Monday.  I will let you know.
Thanks
________________________________

**Comment by mxaddict** [comment]
Closing as this is a duplicate of #252
