### ISSUE TITLE
Error on 4.3.0 RC wallet on win 7x32

### ISSUE THREAD

**Issue by Cotyso** [NAVCoin/navcoin-core#243]
I'm getting this error on wallet 4.3.0 version rc

![error](https://user-images.githubusercontent.com/30770844/42723752-d5065e1a-876c-11e8-8b41-48c4a86a916d.jpg)

**Comment by aguycalled** [comment]
Did you do any special action on the wallet before this started happening? Like adding or removing something from the config file (Navtech servers, proposals, etc.)?

**Comment by Cotyso** [comment]
No special action on wallet.just installed on top of 4.2.1 wallet.I attach debug file if it help you.I see that conf file has only a word in it:''undefined''.



[debug.log](https://github.com/NAVCoin/navcoin-core/files/2195025/debug.log)
