### ISSUE TITLE
Bootstrap issue with testnet

### ISSUE THREAD

**Issue by sakdeniz** [NAVCoin/navcoin-core#244]
When i try to bootstrap on testnet, it creates 2 copy of blockchain.

- blocks (this folder should not)
- cfund (this folder should not)
- chainstate (this folder should not)
- testnet3 (normal)

you can test with this url [https://navcommunity.net/bootstrap/testnet.tar](url)

**Comment by aguycalled** [comment]
fixed in https://github.com/NAVCoin/navcoin-core/commit/119aaca35e4927832cf715d6cbf14b5c75a89e2d
