### ISSUE TITLE
Add taxation assistance to transaction history

### ISSUE THREAD

**Issue by IfaqYurmama** [navcoin/navcoin-core#246]
For German taxation purposes the rewards from staking must be recorded in Euro at the time the stake was received. 

Therefore it would be helpful if the transaction history could keep track of the value of the transaction at the time of completion (does not need to show up in the wallet but needs to be visible when exporting to CSV) or alternatively add a new CSV export format that includes timestamp, amount in NAV, amount in <currency selected> (should be relatively easy to add the ones supported by CMC right?) and address.

**Comment by mxaddict** [comment]
This sounds like a feature that does not belong on the core wallet, maybe a companion app that processes the CSV history might be more useful.

**Comment by mxaddict** [comment]
I think this might be out of the scope of the core wallet and should be done via a tool that uses core wallet tx history.
