### ISSUE TITLE
GUI not rendering correctly when displayed in high res on Windows 10

### ISSUE THREAD

**Issue by matt-auckland** [navcoin/navcoin-core#252]
Reports of users experiencing GUI warping at high resolutions. (3 cases, 2 confirmed at the same resolution)
OS: Windows 10
Screen Res: 3840x2160

Conjecture: Font size is increasing but the area for the font to render in isn't changing size to accommodate

![image](https://user-images.githubusercontent.com/12672050/43107948-92d0e7de-8edf-11e8-8c34-35229e83bebd.png)

**Comment by mxaddict** [comment]
I tried this, and seems it's not the resolution that is the issue, but the % of the scaling setting in windows 10

When the scaling is 100%, the font seems to fit correctly.

When scaling is increased, the font increases, but the elements containing the font remain the same size which causes the issue.

**Comment by mxaddict** [comment]
This might be related to #427

I will report back here if I can confirm that it is.

**Comment by mxaddict** [comment]
> This might be related to #427
> 
> I will report back here if I can confirm that it is.

It was not related to that issue
