### ISSUE TITLE
Windows compiling source

### ISSUE THREAD

**Issue by tecnoinfoch** [NAVCoin/navcoin-core#260]
I found several problems in compiling the sources for windows.

first:
root@develop-lx:/home/coins/navcoin/src# ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32
bash: ./configure: File o directory not exist

I added the configure file from the bitcoin source now from this error:
config.status: error: cannot find input file: `Makefile.in'

Solution?

**Comment by aguycalled** [comment]
you need to run ./configure on /home/coins/navcoin after running ./autogen.sh

**Comment by tecnoinfoch** [comment]
thank you
this problem is solved now another has arisen when I launch the make

Making all in src
make[1]: ingresso nella directory "/home/coins/navcoin/src"
make[2]: ingresso nella directory "/home/coins/navcoin/src"
  CXXLD    navcoind.exe
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x10f5): undefined reference to `__imp_curl_easy_init'
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x11bd): undefined reference to `__imp_curl_easy_setopt'
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x1269): undefined reference to `__imp_curl_easy_perform'
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x1287): undefined reference to `__imp_curl_easy_cleanup'
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x128d): undefined reference to `__imp_curl_global_cleanup'
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x192e): undefined reference to `__imp_curl_easy_cleanup'
libnavcoin_server.a(libnavcoin_server_a-init.o):init.cpp:(.text+0x1934): undefined reference to `__imp_curl_global_cleanup'
/usr/bin/x86_64-w64-mingw32-ld: libnavcoin_server.a(libnavcoin_server_a-init.o): bad reloc address 0x0 in section `.data'
collect2: error: ld returned 1 exit status
make[2]: *** [navcoind.exe] Errore 1
make[2]: uscita dalla directory "/home/coins/navcoin/src"
make[1]: *** [all-recursive] Errore 1
make[1]: uscita dalla directory "/home/coins/navcoin/src"
make: *** [all-recursive] Errore 1
root@develop-lx:/home/coins/navcoin#

**Comment by aguycalled** [comment]
try using gitian to build the binaries:
https://github.com/NAVCoin/navcoin-core/blob/master/doc/gitian-building.md

**Comment by aguycalled** [comment]
closing
