### ISSUE TITLE
Could I know how NavCoin raw tx are generated?

### ISSUE THREAD

**Issue by cjconstante** [NAVCoin/navcoin-core#261]
I remarked playing with the https://coinb.in/ source code that:
1.I was able to generate NavCoin wallet using same pub and priv bytes than navpay web UI
2.Not able to encode a tx using the same coinb.in encode/decode process. Hex generated by the nav wallet are half size than the bitcoin one.
So my question is, is anyone by luck could tell me what's different between the raw transaction creation between Bitcoin and NavCoin, not in terms of createrawtransaction but more like using the coinb.in soure code which use coinjs

**Comment by aguycalled** [comment]
navcoin transactions have two more fields:
- time - 4 byte integer after version
- strdzeel - arbitrary size vector decoded as a string containing metadata

if you are more precise with your question i might be able to help you, but anyway i'd recommend you using our port of bitcore-lib (http://www.github.com/encrypt-s/bitcore-lib).

**Comment by cjconstante** [comment]
Sure, thanks. Let me check it. I am going to see if your reply can help me.

**Comment by bitcoin4cashqc** [comment]
> our port of bitcore-lib (http://www.github.com/encrypt-s/bitcore-lib)

I checked it and there is few nav coin documentation, it's all the original bitcoin one!

I'm also trying to generate transactions fro txout and wif privatekey, and I get tons of error loading this bitcore-lib into my code and I need to guess every args since bitcoin one are different.

I currently get invalid list[i] from the concat function trying to use this code:

```
` r.txNav = function(){
		 	var nmcNet = bitcore.Networks.get('livenet')
			    	var privateKey = new bitcore.PrivateKey('NL9YqKuG1jtJuWgJQ3v8Wt1mAcXW2hcAMU',nmcNet);
			    	var utxo = {
			    	  "txId" : "115e8f72f39fad874cfab0deed11a80f24f967a84079fb56ddf53ea02e308986",
			    	  "outputIndex" : 0,
			    	  "address" : "17XBj6iFEsf8kzDMGQk5ghZipxX49VXuaV",
			    	  "script" : "76a91447862fe165e6121af80d5dde1ecb478ed170565b88ac",
			    	  "satoshis" : 50000
			    	};

			    	var transaction = new bitcore.Transaction()
			    	  .from(utxo)
			    	  .to('1Gokm82v6DmtwKEB8AiVhm82hyFSsEvBDK', 15000)
			    	  .sign(privateKey);
			    	return transaction;
			    }`
```
