### ISSUE TITLE
Proposal hangs at waiting for funds.

### ISSUE THREAD

**Issue by red010b37** [NAVCoin/navcoin-core#283]
If the community fund is empty and a proposal is accepted it correctly enters the "waiting for funds" state. - this is correct. 

But when you load up the community fund with `donatefund`, the proposal state does not update and hangs in that state and therefore is never accepted. - and you can generate thousands of blocks with no effect

The proposal also never expires as it is accepted - this is correct it just leaves the proposal in perpetual limbo.

**Comment by aguycalled** [comment]
i'm not able to replicate. can you provide more details?

`$ ./src/navcoin-cli -regtest cfundstats
{
  "funds": {
    "available": 0.00010000,
    "locked": 0.00000000
  },
  "votingPeriod": {
    "starting": 720,
    "ending": 900,
    "current": 898,
    "votedProposals": [
      {
        "str": "test",
        "hash": "563d99006a09335882ba07bf0ec3ab755fc13f05d2a472bc897d4a61a97b910c",
        "amount": 1000000000,
        "yes": 178,
        "no": 0
      }
    ],
    "votedPaymentrequests": [
    ]
  }
}
$ ./src/navcoin-cli -regtest listproposals
[
  {
    "version": 2,
    "hash": "563d99006a09335882ba07bf0ec3ab755fc13f05d2a472bc897d4a61a97b910c",
    "description": "test",
    "requestedAmount": "10.00",
    "notPaidYet": "10.00",
    "userPaidFee": "0.0001",
    "paymentAddress": "mogsGDNtVr8fw1BMd29v37tNHcxYjDm55P",
    "proposalDuration": 36000,
    "votesYes": 179,
    "votesNo": 0,
    "votingCycle": 2,
    "status": "accepted waiting for enough coins in fund"
  }
]
$ ./src/navcoin-cli -regtest donatefund 1000
05af70b580bc3919945a5856ada320887ab5a16f700fa6973fd226e04419d91d
$ ./src/navcoin-cli -regtest generate 180;./src/navcoin-cli -regtest listproposals
[
  "f1bfa38efa30a8870612d57d505163aa302b15535fb5a503716775e48dc7e940", 
..... 
  "2357b0596d8faf8c4c7728fd991e178660067ed6fc3e83605a7f9a993d276993"
]
[
  {
    "version": 2,
    "hash": "563d99006a09335882ba07bf0ec3ab755fc13f05d2a472bc897d4a61a97b910c",
    "description": "test",
    "requestedAmount": "10.00",
    "notPaidYet": "10.00",
    "userPaidFee": "0.0001",
    "paymentAddress": "mogsGDNtVr8fw1BMd29v37tNHcxYjDm55P",
    "proposalDuration": 36000,
    "expiresOn": 1535266490,
    "votesYes": 179,
    "votesNo": 0,
    "votingCycle": 2,
    "status": "accepted",
    "approvedOnBlock": "d528af0098496e38bc8832da3a3fdceff6e165ca1f755dfd9874f9f25b5c934e"
  }
]
`

**Comment by red010b37** [comment]
This is is fixed now. I will close it
