### ISSUE TITLE
cfund - createproposal allows negative duration input, causes generate RPC to fail

### ISSUE THREAD

**Issue by marcus290** [NAVCoin/navcoin-core#285]
The 3rd argument "duration" allows a negative value, which is converted to a positive value. 

Not sure exactly how they are converted, but it looks like bitwise AND over the last 32 bits.

The proposals are still created while the blockchain has a height less than 300. Around 300 blocks, a proposal with negative duration will (i) not be included in listproposals; and (ii) cause "generate" RPC in regtest to fail (tinyformat will throw an error).
![screenshot from 2018-08-29 15-39-37](https://user-images.githubusercontent.com/36244342/44764242-da47f280-aba2-11e8-8df4-2f2b4733f5ac.png)

**Comment by aguycalled** [comment]
solved
