### ISSUE TITLE
QT: Converts navcoin://<address> to lowercase and therefore invalidating the address

### ISSUE THREAD

**Issue by dantudor** [NAVCoin/navcoin-core#291]
Deep linking an address as a recipient of a new transaction converts the address to lowercase.

`<a href="navcoin://mjBAWhVyeU37b18SLg2bQzsdcfXJs8jy3z">Link</a>`

This issue was raised in bitcoin core wallet: 
[github.com/bitcoin/bitcoin/issues/11645](https://github.com/bitcoin/bitcoin/issues/11645)

The suggestion there was that the correct URL input format should actually be:
`navcoin:mjBAWhVyeU37b18SLg2bQzsdcfXJs8jy3z` omitting the `//`

The solution in [PR:12723](https://github.com/bitcoin/bitcoin/pull/12723) was to stop attempting to support bitcoin:// throws an error instead. Bitcoin now only supports bitcoin: for deep linking.

Happy to port the pull request from bitcoin over if agreed that is a solution navcoin values.

**Comment by aguycalled** [comment]
we should apply that patch to navcoin core too. feel free to take ownership of this ;)
