### ISSUE TITLE
Community fund proposals status can revert from `accepted waiting for end of voting period` to `pending`

### ISSUE THREAD

**Issue by dantudor** [NAVCoin/navcoin-core#293]
Once a community fund proposal received sufficient yes votes the status will change to `accepted waiting for end of voting period`.

I believe this happens too early. In the example below the proposal is labelled with the above status after 92 positive votes (maybe earlier, just where i stopped). But if there are 50 votes to reject in the same cycle the the proposal status changes back to `pending` and the proposal fails to progress.

Should the status only change to `accepted waiting for end of voting period` once there is no possibility for it to be reverted?

```
  {
    "version": 2,
    "hash": "b49178f0d4aae16f5dfe2f2e78ac4f87502c580afeea29e6e8cbeb59b2e3766f",
    "blockHash": "b328a0959045b0f32cfb06f7eafcc8be3e0e9dfd0587e88b06f62255ceea2e2d",
    "description": "Pass",
    "requestedAmount": "1.00",
    "notPaidYet": "1.00",
    "userPaidFee": "0.0001",
    "paymentAddress": "mq6TFnxGGU778DQqGXFY7yZRuJwLuLtJaY",
    "proposalDuration": 3200,
    "votesYes": 92,
    "votesNo": 0,
    "votingCycle": 4,
    "status": "accepted waiting for end of voting period",
    "state": 0
  }
```

```
  {
    "version": 2,
    "hash": "b49178f0d4aae16f5dfe2f2e78ac4f87502c580afeea29e6e8cbeb59b2e3766f",
    "blockHash": "b328a0959045b0f32cfb06f7eafcc8be3e0e9dfd0587e88b06f62255ceea2e2d",
    "description": "Pass",
    "requestedAmount": "1.00",
    "notPaidYet": "1.00",
    "userPaidFee": "0.0001",
    "paymentAddress": "mq6TFnxGGU778DQqGXFY7yZRuJwLuLtJaY",
    "proposalDuration": 3200,
    "votesYes": 92,
    "votesNo": 50,
    "votingCycle": 4,
    "status": "pending",
    "state": 0
  }
```

**Comment by aguycalled** [comment]
I would say status is transitory while state is definitive

**Comment by dantudor** [comment]
Could it give a false positive to a proposal creator?
Such as, Status is 'accepted waiting for end of voting period', therefore I no longer need to promote my proposal to the community. Then the proposal goes on the fail

**Comment by aguycalled** [comment]
I think this is something we can later polish once the fund is live on main net with the required changes in the protocol. closing.
