### ISSUE TITLE
cfund: Invalidating first block of new cycle does not revert proposal votes

### ISSUE THREAD

**Issue by gagor15** [NAVCoin/navcoin-core#303]
On the first block of a new voting cycle, the proposal's `votingCycle` increments and `votesYes` and `votesNo` get set to 0 from their values in the previous cycle.

If this first block of a new voting cycle gets invalidated, the `votingCycle` reverts, but the votes still remain at 0.

I found this by running the `qa/pull-tester/rpc-tests.py cfund-vote` test which fails because of this.
Might be related to #302

**Comment by gagor15** [comment]
Yep, that fixes it.

There is a small side effect for me though:
When expiring, a proposal goes from `'status': 'expired waiting for end of voting period', 'state': 0` to `'status': 'pending', 'state': 3` instead of `'status': 'expired', 'state': 3`

I guess it's just cosmetic, but I couldn't figure out why it happens.
This does not happen for expiring payment requests.

**Comment by gagor15** [comment]
I made a pull request solving this: aguycalled/navcoin-core#16.
Please check if it's acceptable.

**Comment by aguycalled** [comment]
fixed
