### ISSUE TITLE
Cfund: paymentrequests summing over the proposal amount paid out from locked funds

### ISSUE THREAD

**Issue by marcus290** [NAVCoin/navcoin-core#307]
steps to replicate on regnet:

- createproposal, for an amount, say 100 NAV and accept it

- (probably don't need this step:) createpaymentrequest, for a small amount say 10 NAV, accept it and let it be paid out 
- create multiple payment requests for amounts less than the proposal amount but summing to more than the proposal amount (say 5x 20NAV) _in the same block_

- If they are created in the same block, they will pass the test in rpcwallet.cpp (line 650):
```
if (nReqAmount <= 0 || nReqAmount > proposal.GetAvailable(true))
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid amount.");
```
- vote through all such payment requests

- amount up to the proposal amount will be accepted and paid out
- amounts above the proposal amount will stay as "accepted waiting for end of voting period" and not be paid out
- but if other new proposals are created and accepted, after 1 or 2 voting periods, the extra payment requests will be accepted and paid out
- the total amount paid to the proposal address will be more than the proposal amount and notPaidYet field will become negative

**Comment by marcus290** [comment]
I think in main.cpp (line 3827), the prequest amount is checked against locked funds:
```
                    if(proposal.fState == CFund::ACCEPTED && prequest.IsAccepted()) {
                        if(prequest.nAmount <= pindexNew->nCFLocked) {
                            pindexNew->nCFLocked -= prequest.nAmount;
                            prequest.fState = CFund::ACCEPTED;
                            prequest.blockhash = pindexNew->GetBlockHash();
                            fUpdate = true;
                        }
                    }
```
but it seems like this is the entire cfund locked funds, so if locked funds are large enough, the extra prequests over the proposal amount will be paid out

**Comment by aguycalled** [comment]
the payment request has to be written individually to the db, the issue is with batch writing
