### ISSUE TITLE
Currency Setting

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-core#309]
Not sure if this is already resolved. Core wallet 4.3.0 home page, when changing the displayed currency in setting, staking info won't change until a reboot while transactions and balance do change once it's adjusted.

Minor issue I guess.

**Comment by mxaddict** [comment]
Created a PR for this here: #453

**Comment by aguycalled** [comment]
Bounty assigned to @mxaddict, pending merge

**Comment by mxaddict** [comment]
@aguycalled NRXfZ1egFxMSUsc4Ufpi4Lm7DdXStYmeBG

**Comment by aguycalled** [comment]
Paid 74e4165c820abb9a16c1724186ec81452a54846f919c2961618b9e8ddd3092e8

**Comment by mxaddict** [comment]
Closing issue since PR has been merged
