### ISSUE TITLE
Document navcoins other net settings

### ISSUE THREAD

**Issue by red010b37** [navcoin/navcoin-core#310]
Create a document, in the docs folder that display the settings for Testnet, Regnet, Devnet simlar to the one on the homepage - like this:

![image](https://user-images.githubusercontent.com/4919660/46643466-bbdd0a00-cbd8-11e8-97a7-615c84bff3a6.png)

**Comment by mxaddict** [comment]
Not sure if we need this as it's in the main `README.md` file, closing for now.
