### ISSUE TITLE
Cfund: Raw tx injected payment request amount can be negative

### ISSUE THREAD

**Issue by gagor15** [NAVCoin/navcoin-core#311]
When using raw tx injection instead of rpc commands, it is possible to submit and accept a payment request with a negative amount.
This also increases the global locked amount of the community fund.

When the request is attempted to be paid out on the 5th or 6th block of the next cycle, the block is invalid.
But if the negative amount is not attempted to be paid, new positive requests can be made and paid out from the amount that we 'owe' to the proposal. 

This is presented in [script](https://github.com/gagor15/navcoin-core/blob/cfund-injections/qa/rpc-tests/cfund-paymentrequest-raw-injection.py), where automatic payment inclusion in miner.cpp was disabled.

**Comment by aguycalled** [comment]
this is fixed, closing
