### ISSUE TITLE
Allow Regtest to optionally continue even if it can't generate a new genesis block

### ISSUE THREAD

**Issue by matt-auckland** [NAVCoin/navcoin-core#320]
At the moment if I want to have two nodes running on the same regtest it's a bit of a mission (I'm not sure how I would do it at the moment).
However we can just use two datadirs that contain the same blockchain data. 
The issue here is that the wallet will shutdown when you launch it in regtest mode if it can't generate a new genesis block.

Therefore I think we should add an option continue with the existing data if we want.

**Comment by aguycalled** [comment]
for the use case you are describing you need to use devnet
