### ISSUE TITLE
getcoldstakingaddress accepts cold-staking addresses as arguments

### ISSUE THREAD

**Issue by djksa** [NAVCoin/navcoin-core#322]
I ran getcoldstakingaddress, and input two cold-staking addresses, and it created a new cold-staking address.

This cold-staking address was the length of only one of the original cold-staking addresses.

It also creates a cold-staking address when you input a non-cold-staking address and a cold-staking address as arguments in getcoldstakingaddress.

**Comment by aguycalled** [comment]
fixed
