### ISSUE TITLE
gettransaction shows wrong data for spending-address to cold-staking address transaction

### ISSUE THREAD

**Issue by djksa** [NAVCoin/navcoin-core#324]
Using navcoin-qt I made a new cold-staking address using two addresses where the private key for each one is in the wallet, then I sent navcoin to the cold-staking address from the spending address and when i inputted the transaction id in gettransaction it said false to the ability for the cold-staking address to stake and true to the ability for the cold-staking address to spend.

**Comment by aguycalled** [comment]
the rights of a cold staking script are mutually exclusive with spending having priority over staking, thats how its coded.

**Comment by aguycalled** [comment]
committed patch f4c9aab

**Comment by aguycalled** [comment]
this opens an issue tho. how would that balance be accounted? normal balance? cold staking balance? both?

**Comment by matt-auckland** [comment]
Yeah we need to have a discussion around how to display this in the GUI

**Comment by aguycalled** [comment]
any idea around this? @matt-auckland @djksa

**Comment by marcus290** [comment]
if both the spending key and the staking key are in the same wallet, then either:

- The spending key was imported into the staking key wallet or vice versa; or
- The cold staking address was created with two addresses from the same wallet.

If both keys are in the same wallet, doesn't this defeat the purpose of coldstaking in the first place? I couldn't find any way to remove keys from a wallet after adding them, so essentially, the coldstaking address is made redundant.

Maybe we could stop either event occurring at the source instead? (i.e. stop two keys from being in the same wallet in the first place at importprivkey() and getcoldstakingaddress())

**Comment by matt-auckland** [comment]
Can we close this @aguycalled @marcus290 ?

**Comment by aguycalled** [comment]
closing
