### ISSUE TITLE
validateaddress func on coldstakingaddress with only spendingprivkey imported does not display spendingpubkey

### ISSUE THREAD

**Issue by djksa** [NAVCoin/navcoin-core#325]
When I create a coldstakingaddress with an imported privkey for my staking address, validateaddress func on the coldstakingaddress shows a stakingpubkey. When I import both the spendingprivkey and stakingprivkey, validateaddress func on the coldstakingaddress shows both the spendingpubkey and stakingpubkey. When I delete the wallet.dat file and only import the spendingprivkey, then do validateaddress func on the coldstakingaddress previously generated, the output does not display the spendingpubkey.

**Comment by aguycalled** [comment]
ceeba4b fixed
