### ISSUE TITLE
getrecievedbyaccount always returning zero in regtest

### ISSUE THREAD

**Issue by djksa** [NAVCoin/navcoin-core#330]
booted up fresh regtest client
called staking false 
caled generate 300
called getrecievedbyaddress on only address generated
returned 0

**Comment by djksa** [comment]
Actually it shows the right amount when I send to a newly generated address, generate 1 block then call getrecievedbyaddress on the new address

**Comment by craigmacgregor** [comment]
What address holds the coins generated by the first 300 blocks?

**Comment by marcus290** [comment]
in rpcwallet.cpp (lines 1100 and 1101), `getreceivedbyaddress` intentionally does not include coinbase and coinstake transactions. So I don't think this is any bug with the code.
