### ISSUE TITLE
missing commands in help menu on Console.

### ISSUE THREAD

**Issue by bocyaj** [NAVCoin/navcoin-core#331]
I am using the Windows GUI version of the NAVcoin CORE wallet.  Windows 10 64-bit.

There are two commands missing from the command list output in console when typing 'help': proposalvotelist and paymentrequestvotelist.

**1) proposalvotelist**
when typing 'help proposalvotelist', it returns "help: unknown command: proposalvotelist"

suggest the following to be returned.

```
proposalvotelist

Returns a list containing the wallets current voting status for all active proposals.

Result:
{
      "yes":   List of proposals this wallet is casting a 'yes' vote for.
      "no":    List of proposals this wallet is casting a 'no' vote for.
      "null":  List of proposals this wallet has NOT yet cast a vote for.
}
```
NOTE: the "null" list comes from an enhancement request explained below.

**2) paymentrequestvotelist**
when typing 'help paymentrequestvotelist', it returns "help: unknown command: paymentrequestvotelist"

suggest the following to be returned.

```
paymentrequestvotelist

Returns a list containing the wallets current voting status for all active payment requests.

Result:
{
      "yes":    List of payment requests this wallet is casting a 'yes' vote for.
      "no":     List of payment requests this wallet is casting a 'no' vote for.
      "null":   List of payment requests this wallet has NOT yet cast a vote for.
}
```
NOTE: the "null" list comes from an enhancement request explained below.

Both of these commands show up as an option in the pulldown window when you start typing on the command line so these commands are not completely hidden, but was still difficult to find.

An added enhancement request for both these commands would be to also list the proposals and payment requests that the wallet is not currently voting on.  This would very helpful as it would assist users in identifying new proposals as they are created.  In the suggested help menu output above, I added these in their already in the hopes the team agrees this is needed. :-)

Please let me know if you need anything clarified.

Thanks,
Bocyaj.

**Comment by aguycalled** [comment]
I agree with your suggestion. 4.5.0 will have a graphical interface showing the proposals the user did not cast a vote yet. It's already completed and being tested.
Will fix the help on the console.

**Comment by bocyaj** [comment]
wow that, was fast... and great news. opening another related enhancement request as well.

https://github.com/NAVCoin/navcoin-core/issues/332#issue-387386508

**Comment by craigmacgregor** [comment]
resolved by: https://github.com/NAVCoin/navcoin-core/pull/334#pullrequestreview-182531280
