### ISSUE TITLE
Update Readme with more details on building, testing, etc

### ISSUE THREAD

**Issue by matt-auckland** [navcoin/navcoin-core#344]
At the moment it's a bit hard for people who aren't used to hunting through the repo for build docs and contribution docs to know where everything is. The easier it make it for people to understand where things are and how this repo works (master should not be considered 100% stable for example), the better imo.

I think what Bitcoin has in their readme would be a good starting point for us to begin from: https://github.com/bitcoin/bitcoin/blob/master/README.md

**Comment by mxaddict** [comment]
I just checked the README.md and it has links to building the depends and some other material in `./docs` as well. I think we can close this.
