### ISSUE TITLE
Community Fund Voting Window

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/navcoin-core#357]
When the notification of a new Proposal/Payment Request pops up, and the open window button is clicked, it will always open in the Proposals view no matter if what's new is a Payment Request.

This should be considered when determining in which view the Voting Dialog is open.

The voting dialog should also reflect when there are un-voted entries on the alternative view.

**Comment by matt-auckland** [comment]
The voting window will also always open even if a voting window is already open
