### ISSUE TITLE
bip9-softfork.py unit test fails

### ISSUE THREAD

**Issue by djksa** [navcoin/navcoin-core#360]
`bip9-softfork.py` is left uncommented in `rpc-tests.py` yet the test itself fails locally.

Similar to `segwit.py` in `qa/rpc-tests`, calling `self.nodes[0].getblocktemplate({})` is the cause of the test failure (`segwit.py` is commented out in `rpc-tests.py`).

Travis CI most likely didn't fail because for this test to run you have to include the `-extended` flag after `./rpc-tests.py`

**Comment by djksa** [comment]
similar to segwit.py in qa/rpc-tests, calling self.nodes[0].getblocktemplate({}) is the cause of the test failure.

**Comment by mxaddict** [comment]
Seems related to #361
