### ISSUE TITLE
bip65-cltv.py unit test fails

### ISSUE THREAD

**Issue by djksa** [navcoin/navcoin-core#361]
`bip65-cltv.py` is left uncommented in `rpc-tests.py` yet the test itself fails locally.

Error message: 

```
raise AssertionError("Block sync failed")
```

I suspect this is because multiple generate() function calls are in the file and some of them have args of greater than 1 (such as 100 or 50) which could lead to a race condition.

I will try fix this now with using slow_gen() instead of generate() to generate blocks.

**Comment by djksa** [comment]
Working on the fix. Will be committing changes to my branch: [](https://github.com/djksa/navcoin-core/tree/update-rpc-tests) along with other rpc-test fixes to be merged on the next release of Navcoin-core.

**Comment by mxaddict** [comment]
bip65-cltv.py test is not enabled in the suit as of the moment, might need to create an issue for checking which of these disabled tests need to be fixed and re-enabled.
