### ISSUE TITLE
Fix coldstaking_spending.py

### ISSUE THREAD

**Issue by djksa** [navcoin/navcoin-core#377]
`coldstaking.py` uses the operand `<=` to compare strings on line `84` and the minimum fee required for transactions changes. I added a fix for the assert statements on my [branch](https://github.com/djksa/navcoin-core/tree/update-rpc-tests) using the `satoshi_round()` function but to eliminate all these problems a better fix would be to remove assert statements that check balances and stop specifying fees to send when using `sendtoaddress()`. Instead, to check if the payment went through, we can check using the `txid` if the confirmations are 1 after `slow_gen()` 1 block with staking set to `False`.

**Comment by mxaddict** [comment]
Ran the `coldstaking_spending.py` test in a loop for about 5 minutes, did not fail, so I guess this issue can be closed.
