### ISSUE TITLE
Background image of the OSX install window is mis-sized

### ISSUE THREAD

**Issue by matt-auckland** [navcoin/navcoin-core#379]
Trying to install using the .dmg results in *this* experience.  
<img width="506" alt="image" src="https://user-images.githubusercontent.com/12672050/50119075-76af1580-02b6-11e9-9af6-7ce9013c2143.png">

**Comment by sherlockcoin** [comment]
Fixed. :)

<img width="503" alt="Screen Shot 2019-06-06 at 11 04 34 PM" src="https://user-images.githubusercontent.com/6373918/59053642-84ca1000-88af-11e9-8738-753490a5dd1b.png">

[OSX] macdeployqtplus bug fixes [OSX] #514

**Comment by aguycalled** [comment]
Assigned to @sherlockcoin

**Comment by aguycalled** [comment]
@sherlockcoin can you leave a NavCoin address for the bounty payment once the PR is merged

**Comment by sherlockcoin** [comment]
@aguycalled Thank you very much. :)

Ne2uLHY9EyoNeLqWmXHPCciro586ek64zA 

Cheers!

**Comment by aguycalled** [comment]
Paid ced50fdc3d7677c1f7a112afae2ffff8e841f3ee42f4945127cb1460063c6c93

**Comment by mxaddict** [comment]
Closing as PR was already merged
