### ISSUE TITLE
GUI improve for core wallet - blockchain syncing (Video Demo)

### ISSUE THREAD

**Issue by kakax114** [navcoin/navcoin-core#385]
![suggestionblockchainsync](https://user-images.githubusercontent.com/29662491/50196558-6f683480-03a8-11e9-8ded-1003cc8f0c2d.gif)

**Comment by mxaddict** [comment]
@kakax114 I think porting the GUI from bitcoin-core might be a good solution for this

![Screenshot from 2019-05-19 04-33-07](https://user-images.githubusercontent.com/1060905/57974774-40ee9400-79f0-11e9-9331-0bad3b2c848d.png)
