### ISSUE TITLE
Wallet loading blocks slowly since Community Fund update (~ 3 blocks per/sec).

### ISSUE THREAD

**Issue by sakdeniz** [NAVCoin/navcoin-core#388]
Wallet loading blocks slowly (~ 3 blocks per/sec).

Wallet loading blocks slowly since the Community Fund update.

NavCoin NEXT with 4.5.1 build

Windows 10, intel i5 CPU, 16 GB Ram

**Comment by aguycalled** [comment]
I've observed CountVotes() takes around 250ms per block.

This function should be optimised.

**Comment by aguycalled** [comment]
`    while(nBlocks > 0 && pindexblock != NULL) {
        vSeen.clear();
        for(unsigned int i = 0; i < pindexblock->vProposalVotes.size(); i++) {
            if(!CFund::FindProposal(pindexblock->vProposalVotes[i].first, proposal))
                continue;
            if(vSeen.count(pindexblock->vProposalVotes[i].first) == 0) {
                if(vCacheProposalsToUpdate.count(pindexblock->vProposalVotes[i].first) == 0)
                    vCacheProposalsToUpdate[pindexblock->vProposalVotes[i].first] = make_pair(0, 0);
                if(pindexblock->vProposalVotes[i].second)
                    vCacheProposalsToUpdate[pindexblock->vProposalVotes[i].first].first += 1;
                else
                    vCacheProposalsToUpdate[pindexblock->vProposalVotes[i].first].second += 1;
                vSeen[pindexblock->vProposalVotes[i].first]=true;
            }
        }
        for(unsigned int i = 0; i < pindexblock->vPaymentRequestVotes.size(); i++) {
            if(!CFund::FindPaymentRequest(pindexblock->vPaymentRequestVotes[i].first, prequest))
                continue;
            if(!CFund::FindProposal(prequest.proposalhash, proposal))
                continue;
            if (mapBlockIndex.count(proposal.blockhash) == 0)
                continue;
            CBlockIndex* pindexblockparent = mapBlockIndex[proposal.blockhash];
            if(pindexblockparent == NULL)
                continue;
            if(vSeen.count(pindexblock->vPaymentRequestVotes[i].first) == 0) {
                if(vCachePaymentRequestToUpdate.count(pindexblock->vPaymentRequestVotes[i].first) == 0)
                    vCachePaymentRequestToUpdate[pindexblock->vPaymentRequestVotes[i].first] = make_pair(0, 0);
                if(pindexblock->vPaymentRequestVotes[i].second)
                    vCachePaymentRequestToUpdate[pindexblock->vPaymentRequestVotes[i].first].first += 1;
                else
                    vCachePaymentRequestToUpdate[pindexblock->vPaymentRequestVotes[i].first].second += 1;
                vSeen[pindexblock->vPaymentRequestVotes[i].first]=true;
            }
        }
        pindexblock = pindexblock->pprev;
        nBlocks--;
    }`

This part of the function is taking 93% of the computing time

**Comment by sakdeniz** [comment]
Too much controls in function. Do you think it would be possible to speed up this function?

**Comment by Nova8** [comment]
I have been stuck at block 2273298 it hasn't moved for 2 weeks and only 2 - 7 active connections. 

Any help would be grand?

**Comment by marcus290** [comment]
@Nova8 Make sure you are on the latest version.

If you already are, you can try File>Repair Wallet. Or if that doesn't work, you can try to bootstrap https://info.navcoin.org/knowledge-base/how-to-bootstrap-your-core-wallet/
