### ISSUE TITLE
Add possibility to vote through the spending address

### ISSUE THREAD

**Issue by LordNelsson** [navcoin/navcoin-core#397]
My current situation: 
My Spending address/wallet is on my PC and my cold staking address/wallet is on my ODROID XU4 staking box.

If I understand everything right, I would have to log into my stakebox through either ssh or plugging kb&m in and vote on there.
It would be great to have a way to vote or verify a vote via your spending wallet(in a similar way the cold staking verification works?).
That way you could vote without having to touch your stakebox that often and use your device of choice.

**Comment by matt-auckland** [comment]
Our new stakebox software for the odroid will allow you to change your stakebox's votes from another computer using the web interface. Doesn't resolve your issue but it's a temp solution.

**Comment by mxaddict** [comment]
New voting via lightweight wallets is now possible with 5.0, just waiting for the versionbit to be accepted.
