### ISSUE TITLE
Option to be able to stake to a customised address

### ISSUE THREAD

**Issue by Namugikamawara** [NAVCoin/navcoin-core#399]
Hello, 

I want to define a  customised address on which the stakes will be automatic sent;
Like this,i I have one wallet to stake ,other to spend.
Thanks.

**Comment by chasingkirkjufell** [comment]
Isn't that just cold staking? Set one wallet as your staking address and another as your spending address. All the stakes are only spendable with spending address wallet.

**Comment by aguycalled** [comment]
He means without cold staking, to automatically send only the rewards to a different address.
