### ISSUE TITLE
Issue with MacOS Mojave dark mode

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/navcoin-core#403]
The GUI does not render correctly the colors when using MacOS Mojave in dark mode.

Examples:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/24814046/51570845-8070fd80-1ea0-11e9-8486-22d0ff727032.png">

Address not showing, background for text field amount is black

<img width="871" alt="image" src="https://user-images.githubusercontent.com/24814046/51570865-91ba0a00-1ea0-11e9-98e1-d68e531c36a4.png">

Black background

**Comment by matt-auckland** [comment]
I think for now we just disable dark mode: https://github.com/bitcoin/bitcoin/pull/14593/files

Optimising the wallet for dark mode will be a moderate amount of effort
