### ISSUE TITLE
Create a sample config file on startup if none exists

### ISSUE THREAD

**Issue by matt-auckland** [navcoin/navcoin-core#407]
This is kind of a standard thing in a lot of programs and I think it would make it a lot easier for non-technical users to set up their config files if they knew had examples.

I'm not sure exactly what we should include in the file, one of every command could be excessive.

If a custom datadir/config directory is specified we should probably spawn a file in their too, however this could result in unwanted config files/directory creation if people make typos.

**Comment by aguycalled** [comment]
Paid edf746f8aaaa81e7300c75bd38585256ad3c2e13a17455844ccf203da6e7a251
