### ISSUE TITLE
Reorg on last block of voting cycle causes inconsistent state for expiring proposals

### ISSUE THREAD

**Issue by marcus290** [navcoin/navcoin-core#415]
Some proposal state changes cannot be reversed when invalidating a block. Reversing a proposal state change that was originally :
- from ACCEPTED -> EXPIRED will change it to NIL instead. This proposal could possibly be reaccepted locally by the node.
- from ACCEPTED -> PENDING_VOTING_PREQ will be stuck as PENDING_VOTING_PREQ. The payment requests will persist even if invalidating the block they were created.

It does not affect payment requests because they only ever transition from NIL to the other states.

Replication steps on regtest:
- Create proposal and accept it.
- (Optionally) create a payment request for this proposal.
- Let the proposal expire.
- Move to the end of the voting cycle
- Invalidate the blocks at the end of the voting cycle.

**Comment by marcus290** [comment]
In main.cpp `CountVotes()`, I think these conditional statements at lines 3994 and 4085 will never be entered:
```
                if((!prequest.IsExpired() && prequest.fState == CFund::EXPIRED) ||
                        (!prequest.IsRejected() && prequest.fState == CFund::REJECTED)){
                    prequest.fState = CFund::NIL;
                    prequest.blockhash = uint256();
                    fUpdate = true;
                }
                if(!prequest.IsAccepted() && prequest.fState == CFund::ACCEPTED) {
                    prequest.fState = CFund::NIL;
                    prequest.blockhash = uint256();
                    fUpdate = true;
                }
```
```
                if((!proposal.IsExpired(pindexNew->GetBlockTime()) && (proposal.fState == CFund::EXPIRED || proposal.fState == CFund::PENDING_VOTING_PREQ)) ||
                   (!proposal.IsRejected() && proposal.fState == CFund::REJECTED)){
                    proposal.fState = CFund::NIL;
                    proposal.blockhash = uint256();
                    fUpdate = true;
                }
                if(!proposal.IsAccepted() && (proposal.fState == CFund::ACCEPTED || proposal.fState == CFund::PENDING_FUNDS)) {
                    proposal.fState = CFund::NIL;
                    proposal.blockhash = uint256();
                    fUpdate = true;
                }
```
If a proposal/preq has `fState == EXPIRED`, it also triggers IsExpired(). 

If a proposal/preq has `fState == ACCEPTED` or `fState == REJECTED`, it has recorded nVotesYes and nVotesNo to get to this state. So they will always trigger IsAccepted() and IsRejected() respectively. The only time they do not trigger IsAccepted() or IsRejected() is midway through or at the start of a voting cycle.

This branch is only entered in the last block of each voting cycle, i.e. `(nHeight + 1) % nBlocksPerVotingCycle == 0`, so we never reach these statements midway through or at the start of a voting cycle.


When invalidating a block, we only enter these conditional statements in `CountVotes()` when disconnecting the last block of each voting cycle, i.e. when `(nHeight) % nBlocksPerVotingCycle == 0` because `CountVotes()` is called on `pindexDelete->pprev` which triggers `(nHeight + 1) % nBlocksPerVotingCycle == 0`. So when invalidating blocks, I think `CountVotes()` does not ever update the fState.

**Comment by marcus290** [comment]
The only place where fStates are updated for invalidating a block are in `DisconnectTip()` lines 3688 and 3706:
```
           if(prequest.blockhash == pindexDelete->GetBlockHash()) {
                prequest.blockhash = uint256();
                prequest.fState = CFund::NIL;
```
```
           if(proposal.blockhash == pindexDelete->GetBlockHash()) {
                proposal.blockhash = uint256();
                proposal.fState = CFund::NIL;
```
Which are invoked on `(nHeight + 1) % nBlocksPerVotingCycle == 0` because these blocks are where `blockhash` is recorded.

This means invalidating a block which is `prequest.blockhash` or `proposal.blockhash` will change the fState to NIL. For proposals with `fState == PENDING_VOTIING_PREQ`, it will not be changed to NIL in DisconnectTip() because the proposal.blockhash recorded is from when the proposal was first accepted.  I think fStates will not be changed any other way when invalidating a block.

**Comment by marcus290** [comment]
Same issue for proposals which transition from:
- PENDING_FUNDS -> ACCEPTED
- PENDING_VOTING_PREQ -> EXPIRED

Trying to reverse these transitions will set the fState to NIL.

**Comment by matt-auckland** [comment]
@marcus290 is this still an issue?

**Comment by mxaddict** [comment]
@aguycalled is this still an issue on 5.0? I'm assuming no 👍

**Comment by aguycalled** [comment]
its fixed
