### ISSUE TITLE
rpc tests failing randomly on Travis

### ISSUE THREAD

**Issue by marcus290** [navcoin/navcoin-core#416]
The following rpc tests appear to fail randomly on Travis:
1. ~~cfund-paymentrequest-state-accept-expired-proposal.py~~ (fixed via #418)
2. ~~cfund-proposal-state-accept.py~~ (fixed via #418)
3. coldstaking_spending.py (related to #377)
4. ~~merkle_blocks.py~~ (fixed via #423)
5. wallet.py
6. wallet-hd.py

~~afaik problems with the first 2 tests is related to `time.time()` being inconsistent with block times, which result in a long running time and can cause assert fails immediately after the `while` loop.~~ fixed

Problems with the second 2 tests are related to transaction fees.

**Comment by aguycalled** [comment]
new tests related issue: https://github.com/navcoin/navcoin-core/issues/519
