### ISSUE TITLE
Adjust font text size on windows GUI

### ISSUE THREAD

**Issue by aguycalled** [NAVCoin/navcoin-core#42]
Some elements are not correctly shown on the graphical interface.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T02:15:45+13:00","ped":"2017-11-22T04:42:42+13:00"})

**Comment by jjxtra** [comment]
Are you using 4K monitor? They haven't added proper retina / high dpi support as far as I can tell.

**Comment by aguycalled** [comment]
Please, use #83 to further report about this issue.
