### ISSUE TITLE
Coin Control Sorting

### ISSUE THREAD

**Issue by craigmacgregor** [navcoin/navcoin-core#427]
When i open coin control and i have it in tree mode, i try to sort the coins by confirmations but it doesn't sort correctly. It sorts in descending order by the left most digit instead of right.

eg. the confirmations show:

8766
8755
867
8657

The tx with confirmation 867 should not appear here.

The other digit groupings are the same e.g.

7547
7541
7536
75
7487

The tx with confirmation 75 should not appear here.

Expected behaviour is that it should correctly sort the transactions by confirmation in true numerical descending / ascending order.

NavCoin Core v4.5.2
Linux x86_64

**Comment by aguycalled** [comment]
not seeing it

<img width="265" alt="image" src="https://user-images.githubusercontent.com/24814046/53320428-3e3f3f80-38d6-11e9-855e-6ed260898f79.png">

**Comment by craigmacgregor** [comment]
I'm not sure if it makes a difference but i was in tree mode and also looking at a wallet with cold staking spending keys in it on linux. I'll poke around a bit more and see if i can replicate or refute it on other OS or other transaction types.

**Comment by craigmacgregor** [comment]
in addition to this ticket, the reason why i was in coin control is that i was trying to spend coin's from a specific address. It took quite a long time to use coin control to select the individual inputs i wanted to use. I'm not sure if it's worth the effort, but i was wondering if an extension of the coin control feature could be to add the capability to spend from a specific address instead of choosing specific outputs to use. so if i had multiple addresses in my wallet that act kind of like savings / checking accounts, i could use it to say "spend 5000 NAV from my savings account please" and it would do that and just figure out the best inputs to use that match the address.

Know what i mean? it's probably quite specific to how im using the wallet, but i thought it could be a good feature after my experience. Should i split this out into its own ticket?

**Comment by roast-nav** [comment]
The sort order appears to be alphabetic rather than numeric. In excel, this happens when cells are being treated as text rather than numbers.

**Comment by mxaddict** [comment]
> not seeing it
> 
> <img alt="image" width="265" src="https://user-images.githubusercontent.com/24814046/53320428-3e3f3f80-38d6-11e9-855e-6ed260898f79.png">

I think it might not show on your part, since your inputs are so close together.

I think @roast-nav  is correct, it seems to sort by alpha instead of numeric on my wallet as well.

**Comment by mxaddict** [comment]
Seems I can't replicate this issue on master branch as of now.

![Screenshot from 2019-05-01 17-22-58](https://user-images.githubusercontent.com/1060905/57011743-c8d54f80-6c35-11e9-9b05-a9525fc48783.png)

Was this perhaps fixed already in the 4.6.0 RC changes?

**Comment by aguycalled** [comment]
Might be system-dependent?

**Comment by mxaddict** [comment]
> Might be system-dependent?

Could be, will have to do more testing.

**Comment by mxaddict** [comment]
I did some additional testing.

I found the problem, this bug is caused by the QT version that we use in depends.

I tested with a newer version `5.9.x` and the sorting was working as expected, when tested with the version in `/depends` DIR, the sorting is wrong.

**Comment by mxaddict** [comment]
This issue is also present on windows builds that are using qt `5.7.1`

So it's confirmed a qt 'bug'

![Capture](https://user-images.githubusercontent.com/1060905/57042575-a8d67800-6c97-11e9-954d-9d19a03c28e9.PNG)

**Comment by mxaddict** [comment]
@aguycalled I think there are 2 ways we can solve this, either we patch qt 5.7.1 (Add a new patch file in depends) or we upgrade to qt `5.9`

I can confirm that the bug in 5.9 is squashed.

**Comment by aguycalled** [comment]
i just checked bitcoin core is using qt 5.9.7, so it might be worth a try

**Comment by mxaddict** [comment]
> i just checked bitcoin core is using qt 5.9.7, so it might be worth a try

Ok, i'll get a branch cooking and upgrade to 5.9.7? or should we use latest? (5.9.8)

**Comment by aguycalled** [comment]
5.9.8 includes mostly only security fixes so i'd say 5.9.8
https://blog.qt.io/blog/2019/04/18/qt-5-9-8-released/

**Comment by mxaddict** [comment]
Roger that.

**Comment by aguycalled** [comment]
Paid 191c03a461c0950fb477d4c2584783071e5ad097c01821790a0099eb96678d0d
