### ISSUE TITLE
ZeroCT: qt shows overpaid amounts for private stake rewards

### ISSUE THREAD

**Issue by marcus290** [NAVCoin/navcoin-core#429]
I'm running testnet on ubuntu.

After leaving my wallet to stake with private coins, the transaction history shows some staking rewards which are over 2 NAV which eventually become confirmed and added to the wallet:
![stakerewardgui_bug](https://user-images.githubusercontent.com/36244342/53462617-50bda280-3aa9-11e9-8685-d05b7646d226.png)

After restarting the wallet, the 1000 NAV values are gone, but 79 NAV values remain:
![stakerewardgui 79](https://user-images.githubusercontent.com/36244342/53462635-63d07280-3aa9-11e9-9672-a70c83659c45.png)

I haven't been able to determine yet whether the amounts are overpaid or whether this is simply a display issue.

**Comment by marcus290** [comment]
I haven't been able to check the vin tx, so I couldn't tell how many coins were generated. An example of 79 NAV stake is block `3f0b1e773cd65971b8c3c2ce1801911ac37fc9ec12d1d86171c31cf233cc4be3`, txid `ef9808533e754b5e8a7927bc8e4a08e0b3a921c0798f58c31b4cac79502cc26f`

**Comment by aguycalled** [comment]
committed ` [631c896](/NAVCoin/navcoin-core/pull/412/commits/631c896282b8507149c1368465c98dc6ea4eeb87)` and ` [570ce5f](/NAVCoin/navcoin-core/pull/412/commits/570ce5f97759033cad72f44f4ac83aca16563764)` to provide more debug into this issue

those blocks are wrongly accepted. src/main.cpp line 3238
```
        if (!tx.IsCoinBase() && !tx.IsZerocoinSpend())
```
should be just
```
        if (!tx.IsCoinBase())
```

 investigating why the extra reward is there
