### ISSUE TITLE
banversion crashes the wallet and bandwidth is gigantic

### ISSUE THREAD

**Issue by Panarte** [NAVCoin/navcoin-core#430]
On Windows 10, navcore 4.5.2, adding "banversion" 
banversion=/NavCoin:4.5.1/
banversion=/NavCoin:4.5.0/
banversion=/NavCoin:4.4.0/
banversion=/NavCoin:4.3.0/
banversion=/NavCoin:4.2.1/
banversion=/NavCoin:4.2.0/
banversion=/NavCoin:4.1.0/

in navcoin.config to limit the bandwidth makes the wallet crashing. It starts well, loads the blocks then opens the general windows of the wallet but shut down after 2-3 seconds without any warning.

This issue is secondary (and actually the consequence) of a first one : the bandwidth of the current wallet is enormous = 1 MB/second is transmitted. Limiting the versions seemed a good option but it actually crashes the wallet.

**Comment by LordNelsson** [comment]
I've been getting the same crashes once I add "banversion" to my config.

**Comment by aguycalled** [comment]
duplicate #411
