### ISSUE TITLE
Generate original genesis block for navcoin

### ISSUE THREAD

**Issue by AtomicLemon** [NAVCoin/navcoin-core#431]
Hello, I just wanted to ask how would you generate the Genesis block with a tool like GenesisH0?

The original one, not a new one.

Thanks in advance!

(P.S. Im not trying to make another shitcoin)

**Comment by aguycalled** [comment]
this is not a support channel. closing issue.

**Comment by AtomicLemon** [comment]
I don't need support, but okay

I was literally asking 1 question.
