### ISSUE TITLE
Stake transactions have wrong amount in navcoin-qt when using the spending wallet

### ISSUE THREAD

**Issue by mxaddict** [NAVCoin/navcoin-core#446]
When viewing the navcoin-qt wallet with a spending address that has staked, the stake transactions show the Outpus FULL amount, instead of just the 2 NAV + FEEs

![Screenshot from 2019-04-27 00-32-07](https://user-images.githubusercontent.com/1060905/56822568-0e83c800-6884-11e9-8914-5446f26abffc.png)

![Screenshot from 2019-04-27 00-32-19](https://user-images.githubusercontent.com/1060905/56822570-104d8b80-6884-11e9-979e-2a46098db46a.png)

**Comment by aguycalled** [comment]
fixed in d98fc5fa

**Comment by mxaddict** [comment]
Nice!

**Comment by mxaddict** [comment]
@aguycalled , I have built the current code on the master branch, it seems that the issue was fixed on the `spend` address `wallet.dat`

But might have broken it on the "stake" address, with the last 4.6.0 RC that I tested (Link sent via discord #general) only the "spend" wallet had this issue, not the "spend" wallet is fixed, but the "stake" wallet is broken.

![Screenshot from 2019-04-29 22-59-03](https://user-images.githubusercontent.com/1060905/56905406-b5f63a00-6ad2-11e9-8236-60540430ce1d.png)

**Comment by mxaddict** [comment]
@aguycalled NRXfZ1egFxMSUsc4Ufpi4Lm7DdXStYmeBG

**Comment by aguycalled** [comment]
Paid bd2e04fbcd314facb68e8cdb11b7d6d2282cc4ba1abdf09109f3b23f86ade788
