### ISSUE TITLE
Add a GUI for mnemonic use

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#451]
A new 'Welcome' wizard should guide the user on how to import an old wallet or create a new one with the use of the new mnemonic functionality of v4.6.0

**Comment by mrmetech** [comment]
Hi I would like to do this bounty

**Comment by aguycalled** [comment]
assigned to @mrmetech

**Comment by mrmetech** [comment]
NdTrSEe6bMMvVwNUimxs2BiWkX5Xn9MW7o

**Comment by mxaddict** [comment]
Already on 5.0, and bounty paid, closing issue.
