### ISSUE TITLE
CFund GUI requires wallet unlock to create proposal / payment request.

### ISSUE THREAD

**Issue by craigmacgregor** [navcoin/navcoin-core#457]
Using the new CFund GUI in 4.6.0-rc to create a payment request or proposal requires the user to unlock the wallet. There is no dialog to enter the passphrase to unlock the wallet and create the transaction. There is only an error alert dialog. 

<img width="441" alt="Screen Shot 2019-05-01 at 3 50 56 PM" src="https://user-images.githubusercontent.com/6902746/57005093-f7006280-6c28-11e9-83f4-2c0a9551247f.png">

I had to go to the debug window and use the walletpassphrase command to unlock my wallet before I was able to create the proposal.

Ideally the flow would be the same as creating a regular transaction. The user would be prompted to enter their password and the wallet would only remain unlocked for the duration of creating and signing the transaction then immediately revert to being locked again.

Steps to reproduce;

- Open navcoin-qt
- Encrypt wallet
- Navigate to Community Fund tab
- Try to create a proposal or a payment request

**Comment by craigmacgregor** [comment]
@aguycalled do you want to allocate a bounty to this?

**Comment by francisjyap** [comment]
@aguycalled 

NVRFaYW5PFJFG7xQomPqczjZFSVXAbqh2E

**Comment by aguycalled** [comment]
paid 144b6197e6c3b8e0fb3c1e28d430b44db09ff9f8b484c8186474c6d78f7efbcb
