### ISSUE TITLE
Show logged errors on GUI for easy reporting

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#460]
Entries logged through error() should be categorised and shown on a dedicated dialog of the GUI, so when a user is requesting support he can easily share them if necessary without having to go through the log file.

**Comment by mxaddict** [comment]
> Entries logged through error() should be categorised and shown on a dedicated dialog of the GUI, so when a user is requesting support he can easily share them if necessary without having to go through the log file.

Maybe we should add a tab in the debug window?

**Comment by aguycalled** [comment]
like the idea

**Comment by mxaddict** [comment]
i'll add it then 😄

**Comment by mxaddict** [comment]
@aguycalled PR for this is here: #466

**Comment by aguycalled** [comment]
Paid 0019f290a47ace8c4134cd1f3167d10b2fc1914de903c3799cd73710a8e69e88
