### ISSUE TITLE
Weird empty box in settings/options dialog (Wallet Tab)

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#483]
Weird empty box in settings/options dialog (Wallet Tab)

What is this for?

![Screenshot from 2019-05-16 05-29-12](https://user-images.githubusercontent.com/1060905/57811096-fffe4180-779b-11e9-8188-72ed644c06b6.png)

And can I remove it? :+1:

**Comment by aguycalled** [comment]
I'd say the checkboxes should go inside of the box

**Comment by mxaddict** [comment]
@aguycalled created a PR for this

**Comment by mxaddict** [comment]
Fixed on master
