### ISSUE TITLE
Sanity check of chain snapshot (bootstrap)

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#488]
When a snapshot from an external party is downloaded, the wallet should check for sanity before using it:
- Version of the blocktree db
- Version of the coins db
(any other checks?)

**Comment by mxaddict** [comment]
I can't think of any other checks (I don't have enough exp with the db code)

But didn't @craigmacgregor mention that we should minimize the use of bootstrap?

Maybe we should remove it from newer versions to better enforce the trust-less nature our our blockchain.

Also, I see that DGB and BTC nodes sync headers faster than our node (Or is it just the GUI that represents the progress differently)

I guess if we decide to remote bootstrapping, then we should make the sync run faster if we can?

**Comment by aguycalled** [comment]
yes, for the sake for decentralisation full sync should be promoted over using snapshots, but is convenient to have the option in some scenarios.

you can compare which part of the header-sync is taking longer by running the node with -debug=bench - curious to see the results

**Comment by mxaddict** [comment]
`-debug=bench` does not work with release/gitian builds does it?

By compare, you mean run the same on bitcoin-core and compare to navcoin-core results?

**Comment by mxaddict** [comment]
What about a compromise? 

Disable bootstrap GUI features, but leave the `-bootstrap` param for navcoin.conf and cli.

This way less savy user's will be more likely to just run a normal p2p sync, but someone who needs to get the node up faster can do a bootstrap from a trusted source?

Also, this means that we don't really need to add version checks to the bootstrap file loading process as whoever is using the bootstrap feature will be more likely to already `know` if the bootstrap will be compatible?

**Comment by mxaddict** [comment]
Basically bootstraping can be more of a system's admin or expert user feature

As it stands now, pretty much anyone can do a bootstrap, and I'm sure some users aren't even aware of the implications of doing so are.

**Comment by aguycalled** [comment]
yes. it works the same.

example output:

```
2019-05-18 20:50:29   - Load block from disk: 0.43ms [0.03s]
2019-05-18 20:50:29     - Sanity checks: 1.34ms [1.24s]
2019-05-18 20:50:29     - Fork checks: 0.13ms [0.03s]
2019-05-18 20:50:29       - Connect 2 transactions: 0.19ms (0.095ms/tx, 0.190ms/txin) [0.04s]
2019-05-18 20:50:29     - Verify 1 txins: 0.53ms (0.525ms/txin) [0.08s]
2019-05-18 20:50:29     - Index writing: 0.06ms [0.01s]
2019-05-18 20:50:29     - Callbacks: 0.06ms [0.01s]
2019-05-18 20:50:29 - CFund total CFundStep() function: 6.39ms
2019-05-18 20:50:29   - Connect total: 2.27ms [1.38s]
2019-05-18 20:50:29   - Flush: 6.52ms [0.76s]
2019-05-18 20:50:29   - Writing chainstate: 0.07ms [0.01s]
2019-05-18 20:50:29 UpdateTip: new best=a6ef4ab48e44f9c20efc8557621e7f2b59431b473c37f7c0429f5d904487125b height=453254 version=0x00000007 log2_work=69.934283 tx=948707 date='2016-10-20 08:58:40' progress=0.066697 cache=0.1MiB(410tx)
2019-05-18 20:50:29   - Connect postprocess: 0.29ms [0.05s]
2019-05-18 20:50:29 - Connect block: 9.58ms [2.23s]
```

**Comment by aguycalled** [comment]
> Basically bootstraping can be more of a system's admin or expert user feature
> 
> As it stands now, pretty much anyone can do a bootstrap, and I'm sure some users aren't even aware of the implications.

I can't but totally agree.

**Comment by mxaddict** [comment]
So I guess the PR for this issue should be:

* Version of the blocktree db
* Version of the coins db
* Remove bootstrap GUI option (Replace with a pop-up message saying to check `navcoind --help`)

**Comment by mxaddict** [comment]
Also maybe this change should be in the same release? #385

**Comment by aguycalled** [comment]
> Also maybe #385 should be in the same release?

👍🏻

**Comment by aguycalled** [comment]
> Also maybe #385 should be in the same release?

Different PRs

**Comment by mxaddict** [comment]
Yeah, different PR, but I mean it should have that update if/when we remove the GUI bootstrap option so the sync has more detailed in info :+1: 

Right now the sync is kinda unknown (User can't tell how fast/slow it's going and does not know the ETA either)

**Comment by aguycalled** [comment]
👍

**Comment by mxaddict** [comment]
@aguycalled I these lines seem to check the cfund related data in the the blocks/chainstate after importing a 3rd party bootstrap file:

https://github.com/aguycalled/navcoin-core/blob/ab5fce9af6a63ff1a3b30f34e3df6ff75f3cb717/src/init.cpp#L1654-L1694

What exactly did you mean by "sanity checks" for the bootstrap?

**Comment by aguycalled** [comment]
for example, the db structure could get modified in next versions deriving in unpredictable states if not compatible, therefore the idea of adding version control

**Comment by mxaddict** [comment]
Ahh, I see

So we want to add a version bit to chainstate/blocks?

I assume this needs to be added correct?

And that we would check the version after untar of bootrap, before init?

And if the version is not compatible, we discard and output a warning saying we are not using the bootstrap provided?

**Comment by aguycalled** [comment]
yep! that's what i proposed

**Comment by mxaddict** [comment]
> yep! that's what i proposed

I get it now :+1:

**Comment by craigmacgregor** [comment]
Seems like i missed most of this conversation and it's kind of unrelated but here's a copy of the bash script i use to generate the bootstrap;

https://github.com/craigmacgregor/bash-scripts/blob/master/nav-bootstrap.sh

**Comment by craigmacgregor** [comment]
If there's something you want me to do from that side like sign the tar file so the user knows it comes from the core operated bootstrap server just let me know.

**Comment by mxaddict** [comment]
I think the version bit will be added to the db files so that it will be in the boostrap no matter if it's an official one or just one someone creates from a public node.

**Comment by craigmacgregor** [comment]
Yeah i get that. I was just trying to think what else could be possible.

**Comment by mxaddict** [comment]
Do you think we still need/want this? After all we want to discourage using a bootstrap.

**Comment by aguycalled** [comment]
i think it would still be a good addition

**Comment by mxaddict** [comment]
@aguycalled  @proletesseract Do you think this is still needed?

Current sync speed is decent compared to when we were using the bootstrap.

I think we can just optimize the sync speed even more and completely remove the bootstrap option.

**Comment by aguycalled** [comment]
i think we can close this by now
