### ISSUE TITLE
Implement Dandelion++

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#490]
Dandelion++ works at the network stack preventing observers from establishing links between transactions and the IP of the originator.

More details: https://arxiv.org/pdf/1805.11060.pdf

**Comment by aguycalled** [comment]
In our POS model stakers reveal their addresses through block broadcasting. 

Question: Is dandelion++ applicable to block broadcasting?

**Comment by mxaddict** [comment]
> Dandelion++ works at the network stack preventing external observers from establishing links between transactions and the IP of the originator.
> 
> More details: https://arxiv.org/pdf/1805.11060.pdf

Could someone actually get the ip of the original sender?

Or would that just be a semi accurate guestimate?

**Comment by aguycalled** [comment]
It prevents a node from determining if the node which broadcasted a transaction is its originator even if the adversary controls a big number of nodes observing the network traffic.

**Comment by mxaddict** [comment]
Already on 5.0
