### ISSUE TITLE
Implement BIP151: P2P communication encryption

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#491]
https://github.com/bitcoin/bips/blob/master/bip-0151.mediawiki

**Comment by mxaddict** [comment]
Upstream did not implement this why?

**Comment by aguycalled** [comment]
https://github.com/bitcoin/bips/wiki/Comments:BIP-0151

We need to consider all the arguments.

**Comment by aguycalled** [comment]
https://bitcointools.jonasschnelli.ch/BIP324_BB_2019_V2_MESSAGE_TRANSPORT_PROTOCOL.pdf

**Comment by mxaddict** [comment]
We are using dandelion++ now, can we close this issue?

**Comment by mxaddict** [comment]
@aguycalled does this issue still need working on? or does BLSCT have these changes covered?

**Comment by aguycalled** [comment]
we can close it by now
