### ISSUE TITLE
Enabling coin control causes crash to desktop with segmentation fault error

### ISSUE THREAD

**Issue by go140point6** [navcoin/navcoin-core#496]
Experiencing a crash-to-desktop (CTD) in navcoin-qt when attempting to enable coin control.  GUI exits leaving "Segmentation fault (core dumped)" in terminal.

Debug log reports:
2019-05-22 21:12:15 GUI: Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt.
You must not let any exception whatsoever propagate through Qt code.
If that is not possible, in Qt 5 you must at least reimplement
QCoreApplication::notify() and catch all exceptions there.

NavCoin version v4.6.0.0-bb51359-dirty downloaded from navcoin.org/en/wallets for Linux (navcoin-4.6.0-x86_64-linux-gnu.tar.gz)

Tried coin control before staking and after staking, CTD in all cases.  Navcoin-qt appears to be working fine before and after staking, and is stable until attempting to enable coin control.

System specs: 
OS: Lubuntu 19.04 (Disco Dingo) with LXQt desktop
Celeron g1610 LGA 1155 (3rd gen - ivy bridge)
8G RAM

Note: Running two wallets on this hardware, NAV and PIVX.  RAM utilization reported by htop is about 5.2G.

Edit: Attempting to enable coin control in my PIVX wallet results in the same CTD.  Suggests to me OS/hardware issue.  Will attempt to duplicate in VM on different OS.

**Comment by go140point6** [comment]
I have no issue on a VM running 18.04.2 LTS or 19.04.  Suggests to me either something specific to my hardware or perhaps due to connecting remotely through RDP?

**Comment by mxaddict** [comment]
@go140point6 what DE do you run on the VM? your main machine is LXQt right?

**Comment by go140point6** [comment]
Correct, the physical workstation is Lubuntu 19.04 using default LXQt.  The VM running 19.04 was default LXQt as well.  I also tried with 18.04 using the LXDE (default I believe) to see if that changed anything.  No issues running either VM with navcoin-qt and enabling coin control.  Issue seems to be limited to my physical machine which I was connecting to via RDP.  Later tonight I'll try direct on that machine to eliminate the RDP session as an issue and update accordingly.

**Comment by mxaddict** [comment]
what version of libqt/qt in on main machine vs vms?

**Comment by go140point6** [comment]
not sure how to find that info definitively... pretty vanilla install of Lubuntu with an dist-upgrade.  Tried it direct on my system and same results with the CTD.  Installed a clean VM w/ 19.04, updated it, and no issues setting coin control.  I seem to have eliminated everything but the physical hardware the wallet is running on... since it happens to my PIVX wallet also on that hardware, I'm really suspecting my hardware.  Not sure how to troubleshoot beyond getting another physical workstation and install the wallet.

**Comment by mxaddict** [comment]
I don't think it's the hardware, cause if it was hardware related then it would also crash in the VM

More likely a package on that system is not behaving nicely with QT

**Comment by go140point6** [comment]
Ah, sorry for the confusion.  The VM's were not on that hardware (but good idea).  I created VM's on two other machines, an older 2nd gen i5 and a newer 7th gen i7.

I suppose this issue is not really an issue, just something specific to either my hardware or my installation and setup of the OS.  I guess I'll just have to rebuild from scratch and test out enabling coin control before I do any customization or setup.  Perhaps creating a VM on that hardware directly would help narrow it down as well before I do.

A couple questions before I close this out as a non-issue:
1. Where is that coin control setting kept?  Does it follow the wallet.dat (so can I move it to my VM, set it, and move it back and expect to see it set assuming it doesn't crash on load)?
2. Is the only way to set coin control through navcoin-qt or can I do it via the cli?  I generally run the wallet headless... is there any way to interact with coin control from the cli or is it strictly something for the gui?

My desire to see how the coins are grouped is what started all this for me.  I'm curious if I can do that from the cli assuming I can get the setting enabled.

Thanks for the help.  I appreciate your time, sorry it appears to be a goat rope on my part.

**Comment by aguycalled** [comment]
you can find the qt configuration file in ~/.config/NavCoin/NavCoin-Qt.conf
address groupings can be seen using `listaddressgroupings` with navcoin-cli, and you can select which outputs you will spend constructing, signing and sending a raw transaction with `createrawtransaction`, `signrawtransaction` and `sendrawtransaction`. do not forget to include a change output or you would end up paying a enormous fee

**Comment by go140point6** [comment]
Ah, thanks.  I didn't even notice that there... looks like I'm running QT version 5.7.1 too, btw, was trying to figure out based on packages installed before and not having much luck.

I set coin control to true manually in the NavCoin-Qt.conf file and it allowed me to launch and shows the groupings using Inputs on the Send tab now.  Haven't interacted much with it but it seems stable and gets me where I wanted to go.  I don't intend to do any sending, etc. from CLI, just was curious how my coins were grouped.

Interestingly enough, I see this error in the lxqt debug log when I try to apply the coin control enabled setting from the gui and it crashes:
`Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1104, resource id: 35651597, major code: 18 (ChangeProperty), minor code: 0`
`QXcbConnection: XCB error: 3 (BadWindow), sequence: 1111, resource id: 35651597, major code: 18 (ChangeProperty), minor code: 0`

In any case, thanks for the help you both provided.  I don't think this is something to fix on the navcoin side, likely something I have going on with my installation/hardware.  As long as you agree, I'll close out the case (or you can feel free to do that).  Thanks again.

**Comment by aguycalled** [comment]
closing issue, will reopen if needed

**Comment by danirabbani90** [comment]
I have the similar issue enabling coin control but my Qt wallet is not fixed although it runs fine in root but in the user its not fixed can anyone help me out please ?

**Comment by mxaddict** [comment]
Sounds like a permission issue.

Is your datadir in /root or in /home/user?

**Comment by go140point6** [comment]
Yes, that does sound permission based.

My original segmentation fault issue was 100% hardware problem on my end.  I moved my wallet to a cloud VPS for a few weeks as a test and zero problems.  I moved back locally to new hardware (Pi 4!) and haven't had a single issue (running Nav and two other PoS wallets at the same time).

**Comment by danirabbani90** [comment]
Hi my data dir is in /home/user but the segmentation fault still presists in the debug log it says Gui insert action??  Does anyone know how to fix
