### ISSUE TITLE
#include <> vs #include "" for headers

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#503]
I noticed that upstream bitcoin-core has changes related to

```
#include <header.h>
// VS
#include "header.h"
```

Referenced here: https://github.com/bitcoin/bitcoin/pull/11651

Do you guys think we should do the same?

It makes since to have all header includes use `<>` as it will make the files included relative to root of the project instead of relative to the file including it.

**Comment by mxaddict** [comment]
Let me know what you think @proletesseract  @aguycalled

**Comment by aguycalled** [comment]
agree with the change

**Comment by alexeyneu** [comment]
`<>` makes it related to say `/usr/include` among others. It's not cool . You never know whats installed there by third-party guys who may install to it  `bitcoin.h` with no regret. And my bet is that it will have priority(sometimes haha).

**Comment by mxaddict** [comment]
> `<>` makes it related to say `/usr/include` among others. It's not cool . You never know whats installed there by third-party guys who may install to it `bitcoin.h` with no regret. And my bet is that it will have priority(sometimes haha).

I'm not sure you understand what <> does

"" vs <> info here: https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename

**Comment by alexeyneu** [comment]
link you'd post is not more than a conversation . If you're good with foreign `navcoin.h` then use it

**Comment by mxaddict** [comment]
> link you'd post is not more than a conversation . If you're good with foreign `navcoin.h` then use it .
> what i can say fo' sho' is that in msvc things will turn out badly after this

What I'm saying is that is also a concern with "", if someone is able to get a header into your root controlled file system I think you have bigger issues to worry about :+1:

**Comment by mxaddict** [comment]
The "" syntax will behave like <> if the file required is not in the relative path and continue to search like <> in most compiler implementations.
