### ISSUE TITLE
wallet address not fully visible in 'transactions' area of the 'Home' tab

### ISSUE THREAD

**Issue by bocyaj** [NAVCoin/navcoin-core#51]
if an wallet address does not have a label, the transactions section of the home tab is not able to fully show the wallet address.

I think this is related to the font issue on Windows, I am running the wallet on Windows 10 Pro 64-bit and have a newer beta version of the wallet  (v4.0.0.0-74f7b08-dirty)

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T04:42:42+13:00","ped":"2017-11-22T07:09:38+13:00"})

**Comment by aguycalled** [comment]
Please, use #83 to further report about this issue.
