### ISSUE TITLE
Connections stuck around 8 even with inbound 44440 open

### ISSUE THREAD

**Issue by go140point6** [navcoin/navcoin-core#513]
@aguycalled asked me to open this issue even though he can't duplicate on his setup.  I can never seem to get more than 8 or 9 connections for Nav (only occasionally I see 9).  Currently running two other wallets on their respective ports on this box... one is sitting at 19 connections, another is sitting at 105 as of this post.  No change if I stop the other wallets leaving Nav the only one running. Not sure why Nav doesn't increase.  Issue doesn't seem to affect my ability to stake, I've received rewards at expected intervals over the last couple weeks no problem.

Running 4.6.0 wallet as a daemon from command line.  The box is a 3rd Gen i7-3770 w/ 16G RAM with htop showing very low CPU and about 30% RAM utilization.

- I have verified port forwarding is open to 44440 (off-site with ncat).  Double-checked by @aguycalled 
- uPnP is enabled on my router (if it matters)
- time seems to be in sync
- Not running any VPN
- External IP is  dynamic from ISP (but hasn't changed in a long time)
- Internal IP is technically dynamic but fixed with a reservation by my router
- I've added all the current working peer nodes listed (-addnode to navcoin-conf), no change
- I've removed everything but rpcuser/rpcpassword from navcoin-conf, no change
- I've tried limiting to just IPv4 in navcoin-conf, no change

I don't know if this issue is just some quirk with my setup (perhaps that particular port and my ISP?).  Things seem to be working well enough, just wondering why my connection count remained low.  Any additional detail needed, let me know.

**Comment by aguycalled** [comment]
as a note to this, i was able to remotely connect to the node manually

**Comment by mxaddict** [comment]
@go140point6 what OS are you running the node on?

**Comment by go140point6** [comment]
Yeah, I guess that would be a good piece of information:

Lubuntu 19.04

**Comment by mxaddict** [comment]
I'll test a node on that distro and see if I can replicate the issue.

**Comment by mxaddict** [comment]
@go140point6 @aguycalled  I was able to replicate this

I had a node running behind a router and port 44440 open + upnp enabled (At router and wallet)

Was not getting inbound connections

It was because the dns broadcast was not working.

I'm not sure what the cause was though, as when I reset the router/modem, it started working.

**Comment by go140point6** [comment]
I'm using UFW as the system firewall currently, are there ports I need to open specifically for uPnP?  Or something else I need to do to the OS to allow it?  I'm not that familiar with that service.  My wifi router only lists it as "enabled" with no explanation (DLink DIR-882 with it's crappy simplified interface).  Weird how the other two wallets seem to happy to take in inbound connections (one more than the other).  Doesn't seem to affect functionality, so things are working with Nav tho.

**Comment by mxaddict** [comment]
If you're able to setup DMZ, it should work better than upnp.

Just expose the whole range for that machine (assuming security is ok on it)

**Comment by mxaddict** [comment]
I think this is a network setup issue, and can be closed.
