### ISSUE TITLE
Fix functional tests

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#519]
We are currently in the process of moving to a new testing suite.

Work has been started in the branch https://github.com/aguycalled/navcoin-core/tree/functional-tests. There are many tests pending to be fixed.

Each fixed test will be paid as a `bounty-low` issue. Pull requests need to be done to be aforementioned branch aguycalled/functional-tests.

Please ask assignment in this thread to avoid working on something someone else is already doing.

**Comment by proletesseract** [comment]
I'll give coldstaking_spending.py a go today

**Comment by proletesseract** [comment]
coldstaking_spending.py

https://github.com/aguycalled/navcoin-core/commit/027f7c6ab9e76af3b6569848271350277617b0ad

**Comment by mxaddict** [comment]
I think we can close this now? Most of the tests are now working nicely on the test suite, master branch is also passing, and the PRs are passing.

**Comment by mxaddict** [comment]
Just re-open if you think there are more tests that need fixing.
