### ISSUE TITLE
OSX gitian build of master branch is funky looking

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#521]
![image](https://user-images.githubusercontent.com/1060905/59201360-d5ea4480-8bcc-11e9-8e2e-4bb3262a2fe0.png)

![image](https://user-images.githubusercontent.com/1060905/59201365-daaef880-8bcc-11e9-8d22-a20d2abd24ab.png)

**Comment by sherlockcoin** [comment]
Was this present in the 4.6.0 branch?

**Comment by mxaddict** [comment]
IIRC it did not, i think it was introduced by an update to QT version in PR #461

**Comment by sherlockcoin** [comment]
Oh I see @mxaddict , and I was thinking my gitian was broken, sigh. 😆

**Comment by mxaddict** [comment]
@proletesseract were you able to test this PR to see if the artifacts in the menu buttons are fixed?

**Comment by mxaddict** [comment]
@proletesseract this should now be solved with PR #557

**Comment by proletesseract** [comment]
reopening to fix directly

**Comment by mxaddict** [comment]
Nice!
