### ISSUE TITLE
Create a GUI for Deployment Voting

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#529]
Currently the wallet votes `yes` by default for all the deployments in a THRESHOLD_STARTED phase. Clients can change this behaviour by using the `-rejectversionbit` parameter.

This should be changed to a no-vote default behaviour and a GUI should be added for assisting users in the vote process. A popup must be shown whenever there's a deployment being voted without a casted vote.

The GUI must show the title and a text description for the deployments being voted.

**Comment by mxaddict** [comment]
Should the daemon continue to vote yes by default? Or would we require people to add the vote to navcoin.conf manually?

**Comment by aguycalled** [comment]
the daemon should vote no by default, only changing to yes by manual action

**Comment by mxaddict** [comment]
ACK

**Comment by mxaddict** [comment]
@aguycalled @proletesseract should we have the vote be not no and not yes by default?

Maybe neutral by default?

**Comment by aguycalled** [comment]
Because nodes can only signal or not signal for a deployment readiness, there is not something like a neutral vote.

Should I assign you this task? ;)

**Comment by aguycalled** [comment]
I'm working on this as part of https://github.com/navcoin/navcoin-core/pull/530

**Comment by mxaddict** [comment]
I think we can close this 😄
