### ISSUE TITLE
Transactions take 6 confirmations but stakes take 50/51 confirmations?

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#534]
send/receive tx take 6 confirmations but stakes tx take 50/51 confirmations?

@aguycalled is this by design or a bug?

**Comment by aguycalled** [comment]
stake maturation of 50 blocks is by design.
6 confirmations for normal tx is inherited from bitcoin and should be adapted

**Comment by mxaddict** [comment]
So the 5/6 block maturity for normal tx should take 50/51?

**Comment by aguycalled** [comment]
i don't think the 5/6 block maturity requirement is enforced in order to be able to spend outputs. it's just a gui indication iirc
the staking maturity requirement is to prevent precomputing of stake kernel hashes

**Comment by mxaddict** [comment]
> i don't think the 5/6 block maturity requirement is enforced in order to be able to spend outputs. it's just a gui indication iirc
> the staking maturity requirement is to prevent precomputing of stake kernel hashes

So nothing to fix then, I'll close the issue.
