### ISSUE TITLE
Staking issue - constant 2 NAV reward everyday

### ISSUE THREAD

**Issue by yraen69** [navcoin/navcoin-core#540]
Everyday I have the wallet open and start staking my NavCoin Core wallet stakes 2 NAV, no more, no less. Tried bootstraping the blockchain three times. Tried uninstall and reinstall, same deal.

v4.6.0.0-bb51359-dirty (64-bit)

Windows 10

![NAV_Stake_Error](https://user-images.githubusercontent.com/17959135/60256891-fa505b80-9904-11e9-9aa2-64afc4b072f3.PNG)

**Comment by mxaddict** [comment]
Woah, that's alot of orphans.

Were you forked, then got back on the main chain?

**Comment by mxaddict** [comment]
Also, depending on the amount of coins you have, you will stake less or more frequently.

Block reward is 2 NAV, so if you stake 1 block, that is normal.

You can check expected reward here: https://static-rewards.nav.community/

**Comment by yraen69** [comment]
Thanks I've done another wallet repair and bootstrap, things look a little better. Appreciate the reply here. Wasn't sure if it was just me or others were having the same problem. Couldn't see any existing issues like this here or on other help forums.

![NAV_Stake_Error_002](https://user-images.githubusercontent.com/17959135/60342320-c0a25200-99e3-11e9-8717-0f86af405ea8.PNG)

**Comment by mxaddict** [comment]
Closing, I think this is resolved @yraen69
