### ISSUE TITLE
I see a stuck payment request on QT version of the wallet

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#542]
Payment Request: 8fcf35e0038f7c7e9d73371cd20c33ddad0e1b85067d1f3f496020a1e5e4d956

Shows on wallet with no voting options

![Screenshot from 2019-06-29 16-02-17](https://user-images.githubusercontent.com/1060905/60381424-4aefc200-9a87-11e9-848d-db61af135960.png)

**Comment by mxaddict** [comment]
@aguycalled have you seen this happen before?

**Comment by aguycalled** [comment]
No, but I'm not a GUI user.

**Comment by mxaddict** [comment]
> No, but I'm not a GUI user.

ACK, I have it happening on my laptop, but not on my desktop at home.

I can't replicate it on my main machine.

**Comment by aguycalled** [comment]
![image](https://user-images.githubusercontent.com/24814046/60459485-9e0d7480-9c41-11e9-879f-9b63ca4b21c0.png)

This is what I see.

**Comment by mxaddict** [comment]
I can no longer replicate this, so I'll just close it for now.
