### ISSUE TITLE
Add a counter to the Community Fund button with count of pending votes

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#548]
The Community Fund button on the top bar menu should show a red badge with the number of elements (proposals, payment requests, etc) which are still waiting to be voted.

**Comment by mxaddict** [comment]
If this is implemented, we can then remove the pop up? :+1:

**Comment by mxaddict** [comment]
NOTE: Goku requested to have the button open the `Proposals` or `Payment Requests` section depending on which has an new entry with no vote

I also think if there are proposals and requests, it should open the section with more new (no vote)

**Comment by aguycalled** [comment]
Instead of completely removing the popup, we could substitute it with a big red warning in the main tab

**Comment by mxaddict** [comment]
> Instead of completely removing the popup, we could substitute it with a big red warning in the main tab

But instead that was the red bubble + the number be for?

**Comment by aguycalled** [comment]
Before the popup we had issues reaching enough quorum on the votings.
I'm afraid that just the red badge on the cfund button could be not enough to get the attention from the users.

**Comment by mxaddict** [comment]
> Before the popup we had issues reaching enough quorum on the votings.
> I'm afraid that just the red badge on the cfund button could be not enough to get the attention from the users.

Ok, what about a notice that was orange/yellow instead? red is a bit painful/ugly looking

I think we already have a notice like this color somewhere (I've seen it) I can't remember what is what for.

**Comment by mxaddict** [comment]
It was basically an orange/yellow notice bellow the main menu buttons

**Comment by mxaddict** [comment]
This one:
![Screenshot from 2019-07-02 01-30-53](https://user-images.githubusercontent.com/1060905/60455487-120f4300-9c69-11e9-8745-3d1c43f94cdc.png)

**Comment by aguycalled** [comment]
I think in this case the warning should be a bit more "annoying" in terms of users really wanting to make it disappear.

**Comment by mxaddict** [comment]
Good point, so same style, but RED background instead?
