### ISSUE TITLE
Wallet does not get connections on Windows 2012 Server R2

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#55]
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-21T09:37:26+13:00","ped":"2017-11-21T13:09:12+13:00"})

**Comment by jhoff80** [comment]
For what it's worth, the same goes for Server 2016.

**Comment by mcxgr** [comment]
Same on 2 servers I tried (both 2012r2). Tried both 32 and 64bit clients, delete roaming folder etc. Nothing works. (FW is off btw, using NAT)

**Comment by aguycalled** [comment]
Could not find much about the source of the issue, i suspect is related to the use of libcurl but can't confirm it. Any help with this issue would be much appreciated.

**Comment by mcxgr** [comment]
Sure, how can I assist?

**Comment by andrea-dev1** [comment]
Same problem, windows 2012 R2 datacenter 64

**Comment by comprensys** [comment]
Same here, Windows 2012 R2 64-bit
Is there still no fix? Or another Wallet we can use and move funds to there. I have coins on this wallet address, but can't get to them because it's unable to connect.

**Comment by aguycalled** [comment]
Wallets are not compatible with Windows 2012 R2 yet.

**Comment by Sebro01** [comment]
hello!
when it is going to be available ?

**Comment by mxaddict** [comment]
Could this be related to #513 ?

**Comment by mxaddict** [comment]
Can anyone with a windows server check that this issue is still around with the release of 5.0?

**Comment by mxaddict** [comment]
Closing issue for now, please feel free to re-open if anyone has additional info that can help in replicating the bug.
