### ISSUE TITLE
Too long list of currency conversions

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#550]
![image](https://user-images.githubusercontent.com/24814046/60451690-ecfcdf00-9c2c-11e9-851b-e6275e42b546.png)
The send confirmation dialog shows a too long list of different currency conversions.
Is this really needed?

**Comment by mxaddict** [comment]
Maybe limit it to NAV + the selected currency?

**Comment by mxaddict** [comment]
@aguycalled Does this look ok?

![Screenshot from 2019-07-02 01-10-17](https://user-images.githubusercontent.com/1060905/60454374-3fa6bd00-9c66-11e9-894e-25dfbd5d16c3.png)

NOTE: my selected currency in the wallet is "PHP" so it shows the value in BTC + Your selected display unit.

**Comment by aguycalled** [comment]
Looks great if you ask me.

**Comment by mxaddict** [comment]
Or should it be Total Amount XXX NAV
(=XXX BTC or XXX DISPLAY UNIT)

**Comment by aguycalled** [comment]
mmm, what about

Total Amount XXX DISPLAY UNIT
(=XXX BTC or XXX NAV if DISPLAY UNIT != NAV)

**Comment by mxaddict** [comment]
![Screenshot from 2019-07-02 01-13-55](https://user-images.githubusercontent.com/1060905/60454555-ae841600-9c66-11e9-9499-c6c064f98670.png)

**Comment by mxaddict** [comment]
> mmm, what about
> 
> Total Amount XXX DISPLAY UNIT
> (=XXX BTC or XXX NAV if DISPLAY UNIT != NAV)

Ok, I like that idea

**Comment by mxaddict** [comment]
Display unit: NAV
![Screenshot from 2019-07-02 01-25-03](https://user-images.githubusercontent.com/1060905/60455193-67972000-9c68-11e9-8386-4ce322969db9.png)


Display unit: BTC
![Screenshot from 2019-07-02 01-25-24](https://user-images.githubusercontent.com/1060905/60455204-6e259780-9c68-11e9-9fa6-f8d765a55620.png)


Display unit: PHP or Any other
![Screenshot from 2019-07-02 01-24-04](https://user-images.githubusercontent.com/1060905/60455227-74b40f00-9c68-11e9-8e65-4698051ac5c1.png)
