### ISSUE TITLE
Icon's inconsistent on navcoin-core

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#552]
Icons on left are BTC icons on right are OURs:
![Screenshot from 2019-07-02 17-26-44](https://user-images.githubusercontent.com/1060905/60501472-aff92100-9cee-11e9-9284-247287d892e3.png)

It seems that our icons are inconsistent in theme/design

I like how BTC's icons are consistent, do you guys think it's worth the work to make these consistent for our project?

**Comment by aguycalled** [comment]
I'll asign a bounty to this.

**Comment by mxaddict** [comment]
> I'll asign a bounty to this.

That escalated quickly :+1: 

Do we have any designer/graphics people that we can have look at this?

**Comment by mxaddict** [comment]
I think we should make all the icons black and consistent theme

The colors of the icons are done via code anyway (They don't actually use the color, they seem to be used as shapes/outlines then filled in with the color via QT code)

**Comment by mxaddict** [comment]
IE, most of the good looking icons are bold/heavy looking, and some of the other icons like the https://github.com/navcoin/navcoin-core/blob/65ad4eb3f6835f840eeed8acd73737bac1f1c55f/src/qt/res/icons/quit.png is skinny/light looking compared to the other icons in the set.

**Comment by onlyoneAdam** [comment]
Hi! This is something that I can do. Can I get it assigned?

**Comment by aguycalled** [comment]
Assigned, please read the reddit thread with the bounty program rules :)

**Comment by mxaddict** [comment]
@onlyoneAdam nice!

**Comment by mxaddict** [comment]
@onlyoneAdam are you working on this?

BTW, I've created a PR with SVG support for the wallet, can you make the new icons `SVG` files and place them in the `src/qt/res/icons/vector`

You can check out the `SVG` icons I've created here: https://github.com/navcoin/navcoin-core/tree/ecc01cc7ed859e8e7f97f04b78d392701ff9662f/src/qt/res/icons/vector

**Comment by mxaddict** [comment]
Those SVGs are single color and are in `256x256` canvas with `10` padding on `top right bottom left`

Maybe we should standardize that spec for new icons/graphics.

**Comment by mxaddict** [comment]
@aguycalled what do you think?

**Comment by onlyoneAdam** [comment]
Hey, yes, im working on it. It sounds perfect, I’ll follow those guidelines.

**Comment by mxaddict** [comment]
Nice, Also, just keep the svg saved as optimized svg with black/#000000 fill (The code can change the icon colors when rendered in the wallet)

**Comment by onlyoneAdam** [comment]
Hey, one thing. Even the red and green icons (the arrows) should be save with black fill?

**Comment by mxaddict** [comment]
Yes, we can color them via code.

**Comment by onlyoneAdam** [comment]
Other question. there is the same icon for "file save" and "receive". Should I keep it like this or better check for the appropriated one?

**Comment by mxaddict** [comment]
> Other question. there is the same icon for "file save" and "receive". Should I keep it like this or better check for the appropriated one?

I think make a new icon for `save` maybe a diskette icon

**Comment by aguycalled** [comment]
i like the diskette idea for `save`

**Comment by mxaddict** [comment]
@onlyoneAdam I see you've created your fork, no need to base it off my branch, you can just base your changes off of [master](../tree/master)

**Comment by mxaddict** [comment]
BTW @onlyoneAdam maybe join discord server if you have not already? https://discord.gg/WNxmRMZ

**Comment by onlyoneAdam** [comment]
sure, ill join now ;)
