### ISSUE TITLE
SVG version of the logo

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#567]
After the last changes in the wallet design, the NAV logo used in the top left corner does not completely match the new aesthetic. 

A new SVG version should be created with the new vibe. Removing the background shadow and/or retouching the color gradients can be possible ideas in that direction.

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/24814046/61230824-26544500-a72b-11e9-8426-9a9a2417a6a2.png">

**Comment by aguycalled** [comment]
Is this something you could have a look at @onlyoneAdam ?

**Comment by mxaddict** [comment]
Also if possible, maybe a new vector version of this icon as well: 
![navcoin](https://user-images.githubusercontent.com/1060905/61231217-481aef80-a75e-11e9-9e40-af958282cf4d.png)

**Comment by onlyoneAdam** [comment]
Hey! 
Sure, I can do that @aguycalled. Do you need any specific size?
@mxaddict do you mean a new design or just having it as a vector file?

**Comment by mxaddict** [comment]
If you have an idea for a better logo, why not! ❤️

**Comment by mxaddict** [comment]
I think for size it's your call since these are unique files and don't need to fit the the sizes of icons. 

I guess the launcher icon just needs to be a square. 

:+1:

**Comment by onlyoneAdam** [comment]
all right! Ill do my best :)

**Comment by aguycalled** [comment]
Paid 51edeca2285bb747a5245018aef9ebf330469644f8bfbac1d961d870a96f3ab9
