### ISSUE TITLE
Simple graphical bug in UI - Community Fund

### ISSUE THREAD

**Issue by yraen69** [navcoin/navcoin-core#576]
See attached, Windows 10 latest NavCoin Core. Just basic graphical bugs where the text for buttons doesn't fit in the allocated space. Should be trivial to fix?

Basically missing the P in Payment Request and the first C in Create Payment Request along with the last T.

![UI_Bug_001](https://user-images.githubusercontent.com/17959135/61535409-c9c39380-aa64-11e9-9b31-f498cda17c50.PNG)

**Comment by aguycalled** [comment]
thanks for reporting, this part of the ui is already being reworked.
