### ISSUE TITLE
Test Project Card

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-core#580]
Don't delete, testing the GitHub Projects API

Lorem ipsum dolor sit amet, consectetur adipiscing elit. In gravida augue ut consectetur vestibulum. Nam volutpat aliquam ligula, vel faucibus purus semper a. In at nisl lacus.

**Comment by mxaddict** [comment]
Ack

**Comment by mxaddict** [comment]
I think we can close this now?
