### ISSUE TITLE
Transaction not in index?

### ISSUE THREAD

**Issue by forkocean-com** [navcoin/navcoin-core#583]
Hi! Get raw transaction trouble...

$ navcoind --version
NavCoin Core Daemon version v4.6.0.0-bb51359-dirty

$ navcoin-cli getblockhash 3365419                                                              
7a0373c1234d1c7d3343478c3b10dd060856ce3324039285ee23fc8cd9895bcd

$ navcoin-cli getblock 7a0373c1234d1c7d3343478c3b10dd060856ce3324039285ee23fc8cd9895bcd
{
...skip...
  "height": 3365419,
...skip...
  "tx": [
...skip...
    "**ba710792ca8e3590e7c9a9714ea9f62b51a1b2f431e21be67a8ac01fb0e65872**"
  ],
...skip...
}

$ navcoin-cli  getrawtransaction **ba710792ca8e3590e7c9a9714ea9f62b51a1b2f431e21be67a8ac01fb0e65872**
error code: -5
error message:
**No information available about transaction**

My config present txindex=1.

**Comment by mxaddict** [comment]
@forkocean-com is this still an issue?

**Comment by mxaddict** [comment]
Closing for now, just re-open if you still have an issue with this.
