### ISSUE TITLE
Parameter "-mininputvalue" have no effect

### ISSUE THREAD

**Issue by R-Marino** [navcoin/navcoin-core#585]
Experimenting with the parameters of the wallet, I realised that the "-mininputvalue" parameter has no real effect.

This is not a parameter that relates to the consensus, and the lack of effect does not involve the general safety. It is only a minor defect.

This parameter was added about a year ago, it could be used to select coins for the stake only if they are higher than a certain value, but it does not.

The cause of the failed effect can be found in the definition of the variable nMinimumInputValue present in line 69 of the file /src/wallet/wallet.cpp.

That line is executed only when the wallet is started, _before_ that the internal structures of GetArg() have actually been set up.
So, whatever the value the user wants to impose on that parameter, the GetArg function always returns the value of 1 COIN.

To correct the operation it is sufficient that the variable is refreshed later.

For example, adding at the beginning of the routine AvailableCoinsForStaking (line 240 same file), which seems to be the only routine that uses this variable, the following line:
nMinimumInputValue = GetArg("-mininputvalue", 1 * COIN);

**Comment by aguycalled** [comment]
Assigned bounty

**Comment by R-Marino** [comment]
I just created the private commit, for a preliminary review.

https://github.com/R-Marino/navcoin-core/commit/fcfea9c99266aec5fab59b0224662a8673963f19

A short notification:
to check the singleline fix, the python test was quite long, about 170 lines, uses from a minimum of 2 to 4 nodes, and to be executed takes between 200 and 270 seconds.
A little exaggerated? ;-)

I imagine that because of this slowness you will want to move it from the automatic test list to the extended one, rarely used.

**Comment by aguycalled** [comment]
@R-Marino I'd invite you to create a pull request with your suggested fix. that way you can also earn the assigned bounty once the pr is reviewed and the change merged.

**Comment by aguycalled** [comment]
This issue is pending payment. @R-Marino could you indicate an address to receive it?
