### ISSUE TITLE
NAV icon used for OSX looks blurry

### ISSUE THREAD

**Issue by magpie17** [navcoin/navcoin-core#595]
### Description
When the navcoin-core wallet is running in the 4.7.0 release candidate the NAV icon that sits in the dock of a Mac computer or laptop is very blurry.

![nav-icon](https://user-images.githubusercontent.com/50758798/63776375-a114a080-c924-11e9-930e-487e5f8b35ce.png)

### Motivation
A high-resolution icon adds to the professionalism of the product being supplied, in this case the navcoin-core wallet.

### Acceptance Criteria

Add any additional acceptance criteria you think should be included to the list below.

- [ ] Description is satisfied.
- [ ] Changes display correctly on desktop / mobile.
- [ ] Translations have been added or ammended as necessary.

**Comment by aguycalled** [comment]
shows fine for me 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/24814046/63970139-b401af00-caa3-11e9-87c2-d7cc22b26d3e.png">
macos mojave 10.14.4 (18E227)

**Comment by mxaddict** [comment]
I've seen this issue on 10.13 before, might not be present on 10.14 or newer.

Seems the icon loads the icns first, then once the wallet boots, it switches to the icon stored in the navcoin-qt binary (I've not found a way to override this behavior yet)

**Comment by mxaddict** [comment]
@aguycalled @proletesseract is this still an issue?

**Comment by magpie17** [comment]
Yes, this is still an issue as I'm still using macOS version 10.13.6 (and using NAV wallet version 4.7.3)

**Comment by aguycalled** [comment]
@magpie17 could you try the new gui? https://build.nav.community/binaries/updated-main-menu/

**Comment by magpie17** [comment]
I've downloaded the new GUI but the icon still looks very blurry. I did notice that when the program first starts, for an instant the icon looks very clear but then changes into a blurry version. I'm afraid it happens too quickly to screenshot the clear icon but I've attached the blurry one for reference. 
![Screenshot at Feb 20 23-31-58](https://user-images.githubusercontent.com/50758798/74934118-8fc2d180-5439-11ea-805b-c6933eb6edfd.png)

**Comment by mxaddict** [comment]
Is this still the case with 5.0 wallet?

**Comment by magpie17** [comment]
I'm using the 5.0 wallet on Mac OS version 10.13.6 (High Sierra) and I can confirm that the icon looks the same as before i.e. it is still blurry.

**Comment by mxaddict** [comment]
I did some investigating, and aparently this issue is related to the OSX version?

I asked a friend of mine to test on latest OSX and the icon issue was not present.

**Comment by mxaddict** [comment]
I think @aguycalled can confirm on his OSX install that this issue is not present.

**Comment by aguycalled** [comment]
<img width="262" alt="image" src="https://user-images.githubusercontent.com/24814046/83748487-90871880-a662-11ea-8b40-a10632eb469b.png">
mojave 10.14.6

**Comment by mxaddict** [comment]
Yeah, so I guess we can close this.
