### ISSUE TITLE
Allow accumulation of the cold staking reward in different addresses.

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#599]
Currently the arguments `-poolfee` and `-pooladdress` can be used to define a cold staking address `pooladdress` where a `poolfee` percentage of the stake rewards are accumulated. Needs to be changed to allow different pairs of addresses and percentages. The changes are only on the client side, those are already scheduled to be enabled in the consensus protocol. When the sum of the percentages from all the addresses is higher than 100% an error must be shown and the wallet must be able to handle the situation. Elements on the UI to modify how the rewards are split should be added.

**Comment by chasingkirkjufell** [comment]
Resolved with #605
