### ISSUE TITLE
Add full encryption support for the wallet db

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#600]
Currently only the private keys are obfuscated when a wallet is encrypted. Adding full encryption support for the whole wallet db (unlocking it on startup) would add privacy in regards to the transaction history and other parameters to be stored in the wallet.db when the new privacy kicks in.

- [x] Encryption of the full contents wallet DB
- [x] Unlock at launch using the GUI
- [x] Unlock at launch using the command line

Bounty: 2500NAV (1 Bounty extra high + 1 Bounty medium)

**Comment by mxaddict** [comment]
@aguycalled I'll take a shot at this :)

**Comment by mxaddict** [comment]
I think a good way to implement this would be to have 2 passwords?

1 for tx data and another for the keys

Issue I see with 1 password for both is that if you encrypt whole wallet.dat with 1 password, that means the wallet will be completely unlocked while running it.

Not just when sending TX.

**Comment by aguycalled** [comment]
yes i agree with doing it like that with 2 passwords. like a PIN for the whole wallet, and then the spending password

**Comment by mxaddict** [comment]
So PIN for the tx data? And password for the keys? Or allow using password for tx data as well?

**Comment by mxaddict** [comment]
People can always just use PIN in the password field anyway 🗡️

**Comment by aguycalled** [comment]
i would allow the pin for decrypting the whole wallet to be alphanumeric and of arbitrary length

**Comment by mxaddict** [comment]
Yeah so user decides how simple/secure it will be (Just like the main password)

**Comment by mxaddict** [comment]
Should I allow a user to encrypt the tx data and leave the keys open? (Strange question, but I know some users might do it out of spite) Hahaha

**Comment by mxaddict** [comment]
I've decide, tx data encryption requires keys to already be encrypted 🍡
