### ISSUE TITLE
Can't remove the first entry in staking destination addresses GUI

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#613]
Can't remove the first entry in staking destination addresses GUI

![Screenshot from 2019-10-23 02-14-37](https://user-images.githubusercontent.com/1060905/67316438-0064ea80-f53b-11e9-9d20-0794cbf22666.png)

# Steps to replicate

* Add multiple staking destination addresses via the GUI
* Save the settings
* Re-open the staking destination GUI pop up
* Try to remove all the destination addresses

# Expected Behavior
* I should be able to remove all the entries

# Actual behavior
* I could only remove all other destinations except the first in the list

**Comment by chasingkirkjufell** [comment]
Tested and I think it's not that the first entry cannot be removed, it's that the community fund entry cannot be removed. Other entries seem to work fine.

**Comment by mxaddict** [comment]
> Tested and I think it's not that the first entry cannot be removed, it's that the community fund entry cannot be removed. Other entries seem to work fine.

Yes, upon further investigation in the code, any NAMED address (The addresses that have a human readable name) could not be removed.

I've created a PR that fixes this.
