### ISSUE TITLE
Setup New Testnet

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-core#626]
Setup a new NavCoin Testnet for Stress Testing.

Ensure we have wide range of different nodes running on the new testnet. Nodes should differ on;

- Geographic Location
- Hardware Specifications
- Operating System
- Self Compiled vs Gitian Built

Post your node details in the comments below to get added to the list and an address to receive some testnet coins.

### Latest Builds

The latest Gitian builds can be found on the [Nav Community](https://build.nav.community/binaries/master) or [NavCore](https://builds.navcore.org/master) servers.

Or you can build your own binaries locally using the instructions in the repo.

### Config Settings

Recommended settings for `navcoin.conf`

```
rpcuser=<username>
rpcpassword=<password>
server=1
testnet=1
debug=1
staking=1
addnode=95.216.214.68
addnode=78.47.190.215
addnode=157.230.157.163
```

Replacing `<username>` and `<password>` with your own RPC username and password if you want to run the RPC server.

### Testnet Nodes

| User | IP | Location | OS | Hardware | Build | 
|:---|:---:|:---:|:---:|:---:|---:|
| @aguycalled | 78.47.190.215 | Nuremberg | Ubuntu 18.04 | 4 GB / 2 vCPUs |  Self | 
| @aguycalled | 95.216.214.68 | Helsinki | Ubuntu 16.04 | 2 GB / 1 vCPUs |  Self | 
| @aguycalled | 78.46.216.22 | Falkenstein | Debian 9 | 4 GB / 2 vCPUs |  Self | 
| @proletesseract | 157.230.157.163 | San Francisco | Ubuntu 18.04 | 4 GB / 2 vCPUs |  Self | 
| @proletesseract | 115.188.131.209 | Auckland | OSX 10.13.6 | 8 GB / 2 Core |  Self | 
| @proletesseract | 115.188.131.209 | Auckland | Windows 10 64bit | 16 GB / 8 Core |  Gitian | 
| @proletesseract | 139.59.20.11 | Bangalore | Ubuntu 16.04 | 2 GB / 1 vCPUs |  Gitian | 
| @proletesseract | 103.125.216.86 | Tokyo | Ubuntu 16.04 | 4 GB / 2 vCPUs |  Self | 
| @sakdeniz | 185.22.187.97 | Istanbul | Ubuntu 18.04 | 16 GB / 8 vCPUs |  Gitian | 
| @roast | 49.196.21.17 | Perth | Ubuntu 18.04 | 8 GB / 8 Core |  Self | 
| @dantudor | 167.99.91.77 | London | Ubuntu 18.04 | 4 GB / 2 vCPUs |  Self | 
| @mxaddict | 159.65.10.63 | Singapore | Ubuntu 18.04 | 3 GB / 2 vCPUs |  Self | 
| @salmonskinroll | 173.174.6.91 | Texas | Windows 10 64bit | 64 GB / 12 vCPUs |  Gitian |

**Comment by mxaddict** [comment]
Agreed, can you or @aguycalled create the initial node? And share the ip?

**Comment by aguycalled** [comment]
Yes, I'm on it

**Comment by aguycalled** [comment]
https://github.com/navcoin/navcoin-core/pull/628 has been merged.

**Comment by aguycalled** [comment]
Testnet node 1

```
IP: 78.47.190.215
Staking: no
Ubuntu 18.04.01
Self compiled
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
2 vCpu
4 GB RAM
40 GB SSD
Location: Nuremberg, Germany
```

**Comment by aguycalled** [comment]
Testnet node 2

```
IP: 95.216.214.68
-testnet -debug -staking=1
Ubuntu 16.04.12
Self compiled
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
ldd (Ubuntu GLIBC 2.23-0ubuntu11) 2.23
1 vCpu
1 GB RAM
20 GB SSD
Location: Helsinki, Finland
```

**Comment by proletesseract** [comment]
Mine is still compiling but the details are;
```
IP: 157.230.157.163
-testnet -debug -staking=1
Ubuntu 18.04.1
Self compiled using depends folder
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
2 vCpu
4 GB RAM
80 GB SSD
Location: San Francisco, USA
```

**Comment by roast-nav** [comment]
I need some detailed instructions to set up test net pls.

**Comment by proletesseract** [comment]
> I need some detailed instructions to set up test net pls.

@roast-nav all you really need to do is run navcoin with this config and it will launch on the testnet and connect to our nodes

```
rpcuser=<username>
rpcpassword=<password>
server=1
testnet=1
debug=1
staking=1
addnode=95.216.214.68
addnode=78.47.190.215
addnode=157.230.157.163
```

just replace `<username>` and `<password>` with your own RPC username and password if you want to run the RPC server.

At this stage you'll need to either compile your own daemon from the latest master, or you can wait until our Gitian builds finish running and I will post up the latest binaries.

**Comment by roast-nav** [comment]
Thanks @proletesseract . I'll wait for the Gitians to finish and use your binaries.

**Comment by proletesseract** [comment]
Testnet node 2 details are;
```
IP: 115.188.131.209
OSX 10.13.6 High Sierra
Self compiled using depends folder
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
2 vCpu
4 GB RAM
80 GB SSD
Location: San Francisco, USA
```

navcoin.conf
```
rpcuser=<username>
rpcpassword=<password>
server=1
testnet=1
debug=1
staking=1
addnode=95.216.214.68
addnode=78.47.190.215
```

**Comment by proletesseract** [comment]
once we have a good list of nodes, we should perhaps commit a testnet readme including this list into the repo

**Comment by sakdeniz** [comment]
IP: 185.22.187.97
-testnet -debug -staking=1
Ubuntu 18.04.3 LTS
Used binary from https://build.nav.community/binaries/master/
8 vCpu
16 GB RAM
100 GB SSD
Location: Istanbul, Turkey

**Comment by roast-nav** [comment]
server=1
testnet=1
debug=1
staking=1
addnode=95.216.214.68
addnode=78.47.190.215
addnode=157.230.157.163
addnode=115.188.131.209
addnode=185.22.187.97

Ubuntu 18.04.3 LTS
https://github.com/navcoin/navcoin-core compiled my own.
intel core i7-2600k CPU @ 3.40GHz x 8
8 GB RAM
100 GB SSD
Location: Perth Western Australia
IP: 49.196.21.17
address for test coins : mjQLGRYfdiMtvp2gPEW3XxZMMeDKpXwXWL

**Comment by proletesseract** [comment]
Testnet node 3 details are;
```
IP: 139.59.20.11
Ubuntu 16.04.1
Gitian build from https://builds.navcore.org/master
1 vCpu
2 GB RAM
50 GB SSD
Location: Bangalore, India
```

navcoin.conf
```
rpcuser=<username>
rpcpassword=<password>
server=1
testnet=1
debug=1
staking=1
addnode=95.216.214.68
addnode=78.47.190.215
addnode=157.230.157.163
```
address: mjUqC76xp9W3ZDsGHwvYE6gPsTJM3BZbui

**Comment by aguycalled** [comment]
Testnet node 3

```
IP: 78.46.216.22
Debian 9
-testnet -debug -staking=0 -txindex=1 -addressindex=1
Self compiled with depends folder
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) 
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
2 vCpu
4 GB RAM
40 GB SSD
Location: Falkenstein, Germany
```

This node will be used to inject transactions and dao entries.

**Comment by dantudor** [comment]
IP: 167.99.91.77
Ubuntu 18.04.2 x64
configure --without-gui
Self compiled using system dependencies
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
2 vCpu
4 GB RAM
60 GB SSD
Location: London, UK

navcoin.conf

testnet=1
rpcuser=<username>
rpcpassword=<password?
rpcport=8332
listen=1
server=1
txindex=1
addressindex=1
spentindex=1
zmqpubhashtx=tcp://*:28332
zmqpubhashblock=tcp://*:28332
zmqpubrawblock=tcp://*:28332
zmqpubrawtx=tcp://*:28332

**Comment by sakdeniz** [comment]
Created a web page to show testnet node details dynamically.

http://navcommunity.net/testnet

**Comment by sakdeniz** [comment]
IP: 37.148.211.167
-testnet -debug -staking=1
Ubuntu 16.04
Used binary from https://build.nav.community/binaries/master/
2 vCpu
4 GB RAM
40 GB SSD
Location: Istanbul, Turkey

**Comment by mxaddict** [comment]
Testnet node:
```
IP: 159.65.10.63
OS: Ubuntu 18.04
RAM: 1GB (2GB Swap)
Location: Singapore
```

Compiled like so:
```
cd depends
make -j2
cd ../
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-pc-linux-gnu
make -j2
```

**Comment by mxaddict** [comment]
@aguycalled `mzj1putA8hVr5YwQ4fFFxS32Egop1ffekx`

![Screenshot from 2019-11-19 19-23-15](https://user-images.githubusercontent.com/1060905/69142582-15b14280-0b02-11ea-8722-e60a3b381ddf.png)

**Comment by mxaddict** [comment]
Closing as new testnet is already done.
