### ISSUE TITLE
Test Sync Scenarios

### ISSUE THREAD

**Issue by proletesseract** [navcoin/navcoin-core#627]
Ensure the latest version of NavCoin Core can always successfully sync from the genesis block.

Types of tests;

- Manual User Testing across a variety of node configurations.
- Review and add to python tests
- Review and add to functional tests

Latest master; https://build.nav.community/binaries/master/

**Comment by aguycalled** [comment]
- Syncing from scratch with
- [ ] All indexes on `txindex=1 addressindex=1 spentindex=1`
- [ ] Only `txindex=1`
- [ ] No indexes.
- Syncing with bootstrap

Both gitian builds for mac, unix and widnows and self-compiled in Ubuntu 18, Ubuntu 19.10 and OSX.

**Comment by aguycalled** [comment]
Hackintosh with Catalina OSX.
No indexes.
Ryzen 3900x, 64GB RAM CL16 DDR4-3600, 1TB NVMe SSD
Successful sync from scratch in 4h 30.

**Comment by proletesseract** [comment]
Syncing from genesis with;

- [ ] Default config (no indexes)

OSX 10.14.5 Mojave
3.1 GHz Intel i7 with 4 Cores
16 GB RAM
Gitian build of release tag 4.7.1

**Comment by proletesseract** [comment]
@aguycalled what about timestampindex?

**Comment by aguycalled** [comment]
> @aguycalled what about timestampindex?

i don't know of services using it, but worth to include it in what we test

**Comment by aguycalled** [comment]
Syncing from genesis test:

**Self build of master @ b8ed018** 

- System dependencies and self compiled `bdb-4.8` and `unbound`.
- `./configure` with `--disable-hardening`.

Tested a headless node:

- [ ] No indexes
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`


Specs:

- 2 vCore - 4096 MB - 80 GB SSD
- Debian 8.11 64bits
- ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
- gcc version 4.9.2 (Debian 4.9.2-10+deb8u2)

**Comment by aguycalled** [comment]
Syncing from genesis test:

**Self build of master @ b8ed018** 

- Used dependencies from `depends` folder

Tested a GUI wallet:

- [ ] No indexes
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] `txindex=1 addressindex=1 spendindex=1` :stopwatch: Sync started `2019-11-17 12:30`
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] Bootstrap
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`


Specs:

- 3.5GHz i7-7500U 2 core - 16 GB DDR4 - 1TB NVMe SSD
- PureOS 8 64bits
- ldd (Debian GLIBC 2.28-10) 2.28
- gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by aguycalled** [comment]
Syncing from genesis test:

**Gitian build of master @ b8ed018** 

Tested a GUI wallet:

- [ ] No indexes :stopwatch: Sync started `2019-11-17 13:30`
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] Bootstrap
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`

Specs:

- Ryzen 3900x 12 core, 64GB RAM CL14 DDR4-3200, 1TB NVMe SSD
- Windows 10 64 bits with Catalina OSX.

**Comment by aguycalled** [comment]
## Syncing test

**Self build with depends folder of master @ b8ed018** 

Tested a GUI wallet:

- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`

Specs:

- Intel Core i7 2,8 Ghz 4 core, 16GB RAM, 1TB SSD
- OSX Mojave 64 bits

**Comment by proletesseract** [comment]
## Syncing test

**Self build of master @ b8ed018** 

- Using compiled libraries in depends directory
- `./configure` with `--disable-hardening`.

Tested a headless node:

- [ ] No indexes - wallet crashed at block `309026`
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] Wallet closed and opened again. Still synced. :white_check_mark:
  - [ ] `verifychain 4 0` rpc command succeeds 
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`


Specs:

- 2 vCore - 4096 MB - 80 GB SSD
- Ubuntu 16.04 64bits
- ldd (Ubuntu GLIBC 2.23-0ubuntu9) 2.23
- gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

**Comment by francisjyap** [comment]
## Syncing test

Gitian build of master @ 676a43b

### Tested a GUI wallet:

* [ ] No indexes (Successful sync from scratch in 3h 15m).
    * [ ] Wallet closed and opened again. Still synced.
    * [ ] verifychain 4 0 rpc command succeeds
    * [ ] After complete sync launch with -reindex=1
    * [ ] After complete sync launch with -reindex-chainstate=1

### Specs:

Intel® Core™ i3-4150 CPU @ 3.50GHz × 4 with 16GB Ram
Running Ubuntu 18.04 LTS

**Comment by mxaddict** [comment]
## Syncing test

Self build of master @ 37fa72e386ad3daff58b92ed7dda1a9b0676a43b

## Tested a GUI wallet:

* [ ] No indexes Successful sync from scratch in 6h 20m
    * [ ] Wallet closed and opened again. Still synced.
    * [ ] verifychain 4 0 rpc command succeeds
    * [ ] After complete sync launch with -reindex=1
   *  [ ] After complete sync launch with -reindex-chainstate=1
* [ ] txindex=1 addressindex=1 spendindex=1 Successful sync from scratch in 12h 30m
    * [ ] Wallet closed and opened again. Still synced.
    * [ ] verifychain 4 0 rpc command succeeds
    * [ ] After complete sync launch with -reindex=1
    * [ ] After complete sync launch with -reindex-chainstate=1
* [ ] Bootstrap
    * [ ] Wallet closed and opened again. Still synced.
    * [ ] verifychain 4 0 rpc command succeeds
    * [ ] After complete sync launch with -reindex=1
    * [ ] After complete sync launch with -reindex-chainstate=1

## Specs:

* Intel® Core™ i7-9750H CPU @ 2.60GHz × 12, 16GB RAM DDR4-3400, 512GB NVMe SSD
* Ubuntu 19.10

**Comment by mxaddict** [comment]
I think we can close this issue now
