### ISSUE TITLE
Test sync v4.7.2-rc

### ISSUE THREAD

**Issue by aguycalled** [navcoin/navcoin-core#650]
Ensure the latest release candidate v4.7.2 of NavCoin Core can always successfully sync from the genesis block.

https://build.nav.community/binaries/v4.7.2-rc/

https://github.com/navcoin/navcoin-core/pull/649

### Template

**(Gitian) build of BRANCH @ COMMIT** 

Tested a GUI wallet/headless mainnet/testnet:

- [ ] No indexes
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 
- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 

Specs:

```
OS
CPU
RAM
SSD
```

**Comment by aguycalled** [comment]
**Gitian build of v4.7.2-rc @ 1b05e35** 

Tested a GUI wallet:

- [ ] No indexes
  - [x] It opens with a previous synced data folder and stays synced.
  - [ ] It is able to sync from scratch. 🕐 started 13.12.2019 11:22
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1`
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] It opens with a previous synced data folder and stays synced.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`
- [ ] Bootstrap
  - [ ] It opens with a previous synced data folder and stays synced.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex=1` 
  - [ ] After complete sync launch with `-reindex-chainstate=1`

Specs:

```
Ryzen 3900x 12 core
64GB RAM CL14 DDR4-3200
1TB NVMe SSD
Hackintosh with Catalina OSX.
```

**Comment by chasingkirkjufell** [comment]
**local Ubuntu 18.10 build of master @ 09f053152761aa254dae27a9da3e338e2e31e671** 

Tested a GUI wallet on mainnet:

- [ ] No indexes
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 
- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 

Specs:

```
Ubuntu 18.10
Intel(R) Xeon(R) CPU E5-1607 v2 @ 3.00GHz
64GB DDR3 RAM
500GB SSD
```

**Comment by aguycalled** [comment]
**local ubuntu 18.04 build of master @ 09f053152761aa254dae27a9da3e338e2e31e671** 

Tested a headless wallet on mainnet:

- [x] No indexes
  - [x] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished. 👍 
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 
- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 

Specs:

```
Ubuntu 18.104
Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
32GB DDR3 
320GB SSD
```

**Comment by chasingkirkjufell** [comment]
**Gitian build of master @ 1b05e35ca44ef05d487bc8027422b655198a2921** 

Tested a GUI wallet on mainnet:

- [ ] No indexes
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished. 
  - [ ] It is able to sync from scratch. 
  - [ ] Wallet closed and opened again. Still synced. 
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [x] After complete sync launch with `-reindex=1`
- [ ] `txindex=1 addressindex=1 spendindex=1`
  - [ ] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [ ] It is able to sync from scratch.
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 
- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 

Specs:

```
Windows 10 Pro
Intel(R) i7 5820k
64GB DDR4 RAM
500GB SSD
```

**Comment by mxaddict** [comment]
**Self build of master @ 23cd3db8718cd354433018b56ecbac41e7cd95eb** 

Tested a GUI wallet:

- [x] No indexes
  - [x] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [x] It is able to sync from scratch. 
  - [x] Wallet closed and opened again. Still synced.
  - [x] `verifychain 4 0` rpc command succeeds
  - [x] After complete sync launch with `-reindex-chainstate=1` 
  - [x] After complete sync launch with `-reindex=1`
- [x] `txindex=1 addressindex=1 spendindex=1`
  - [x] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished. 
  - [x] It is able to sync from scratch.
  - [x] Wallet closed and opened again. Still synced.
  - [x] `verifychain 4 0` rpc command succeeds
  - [x] After complete sync launch with `-reindex-chainstate=1`
  - [x] After complete sync launch with `-reindex=1` 
- [ ] Bootstrap
  - [ ] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [ ] After complete sync launch with `-reindex-chainstate=1`
  - [ ] After complete sync launch with `-reindex=1` 

Specs:

```
Ryzen 3900X 12 core
32GB RAM CL15 DDR4-3600
Ubuntu 18.04
```

**Comment by mxaddict** [comment]
**Self build of master @ 09f05315** 

Tested CLI wallet:

- [x] No indexes
  - [x] When launching the node with an old data folder, the wallet tells the user about the need to reindex and is correctly synced once finished.
  - [x] It is able to sync from scratch. 
  - [x] Wallet closed and opened again. Still synced.
  - [ ] `verifychain 4 0` rpc command succeeds
  - [x] After complete sync launch with `-reindex-chainstate=1` 
  - [x] After complete sync launch with `-reindex=1`

Specs:
```
2 core Digital Ocean VPS
2GB RAM
```

**Comment by mxaddict** [comment]
Since 4.7.2 was released already, I'll be closing this issue now 😄
