### ISSUE TITLE
Add tools page/dialog for running common commands for wallet repair/maintenance

### ISSUE THREAD

**Issue by mxaddict** [navcoin/navcoin-core#674]
Add tools page/dialog for running common commands for wallet repair/maintenance

Options could include, but not limited to:

```
-reindex
-resync
-reindexchainstate
-zapwallettxxes
```

Something that looks like this:

![image](https://user-images.githubusercontent.com/1060905/75796747-11f2b480-5daf-11ea-96b2-07c5e2555e12.png)

**Comment by mxaddict** [comment]
@mrmetech wanna work on this?

**Comment by mxaddict** [comment]
Can be added as a new tab in the debug window/dialog:

![Capture](https://user-images.githubusercontent.com/1060905/75797267-e2907780-5daf-11ea-91bb-07b4572f4f95.PNG)

**Comment by mrmetech** [comment]
Yeah I could work on this

**Comment by mxaddict** [comment]
> Yeah I could work on this

Nice!

**Comment by mrmetech** [comment]
NdTrSEe6bMMvVwNUimxs2BiWkX5Xn9MW7o the address the bounty should be paid to

**Comment by mxaddict** [comment]
Closing as this is already release with 5.0
