### ISSUE TITLE
[RPC] Cant propose an alphanumeric answer 

### ISSUE THREAD

**Issue by dantudor** [navcoin/navcoin-core#687]
When proposing an answer via RPC the command fails when the proposed answer is not a parseable numeric.

`navcoin-cli proposeanswer 8780a29064ada68da8b0f2a5cccef790746b3001f3d04b69d8a2e61eebb5af67 "Satoshi"`
`error: Error parsing JSON:Satoshi`

**Comment by mxaddict** [comment]
Try it like this
```navcoin-cli proposeanswer 8780a29064ada68da8b0f2a5cccef790746b3001f3d04b69d8a2e61eebb5af67 "\"Satoshi\""```

**Comment by mxaddict** [comment]
I'm guessing this is where the error is from: https://github.com/navcoin/navcoin-core/blob/60964e16aa396ced6ab9e9bdcfcc846a72aba01c/src/wallet/rpcwallet.cpp#L1201
