### ISSUE TITLE
Re-add new version pop up

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-core#701]
At some point when we have some resource, we should consider adding this back to notify users that there is a new version of the wallet.

https://github.com/navcoin/navcoin-core/pull/652

**Comment by mxaddict** [comment]
I think I might have added it to the header as a notification, I'll confirm when I get the chance.

**Comment by mxaddict** [comment]
I've checked, and indeed it's not integrated into the notification section either.

**Comment by mxaddict** [comment]
@chasingkirkjufell I think we can close this as I tested it on the master build and the warning shows when a node is staking with higher version number:

![image](https://user-images.githubusercontent.com/1060905/103491609-41a39a80-4e60-11eb-8afb-6683938d15d8.png)

**Comment by mxaddict** [comment]
@chasingkirkjufell @aguycalled do you think we should add the pop up again? or should we stick with the warning message like we have now on the master branch code (I remember adding this message to the UI a while back, just not sure when I added it)

**Comment by aguycalled** [comment]
We removed it because some systems were crashing and we were not able to replicate it.

Von meinem iPhone gesendet

**Comment by mxaddict** [comment]
Closing, feel free to re-open if needed
