### ISSUE TITLE
Update in wallet tx 3d party website to navexplorer.com

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-core#721]
Currently, under setting in display tab, the wallet uses chainz

![image](https://user-images.githubusercontent.com/38635377/84602683-13b42580-ae3e-11ea-8ed5-9b5784961ee3.png)

Suggesting that we change it to https://www.navexplorer.com/

**Comment by mxaddict** [comment]
I think this is already the case:
https://github.com/navcoin/navcoin-core/blob/7c8e25c6d520e8daaf9ca6b6d00646f2782a9eb0/src/qt/optionsmodel.cpp#L74-L76

**Comment by mxaddict** [comment]
Might just be the setting on your machine 😄
