### ISSUE TITLE
[GUI] config variables wrong precedence/order on wallet startup

### ISSUE THREAD

**Issue by chlorocryptos** [navcoin/navcoin-core#729]
Describe the issue:
when starting up the navcoin wallet 5.0.1 with e.g. a 'wallet=mywallet.dat' directive specified in custom config file ('navcoin.conf')
the 'mnemonic startup gui' is presented, although the valid 'mywallet.dat' file is present.
at that point i don't want to create a new wallet, because i have already one....
the 'mnemonic startup gui' vanishes, when the custom wallet file is renamed  to the default 'wallet.dat' name.

i assume the startup logic is flawed, in that the presence of the default file is checked, but not the change of the default setting.
here, the custom configuration should take precedence over the internal set values,
because what sense do config variables for changing default values make, when they are not recognized ?  

What behavior did you expect? 
the 'mnemonic startup gui' should recognize custom config variables of the configuration file or cli specified options.
i.e. check not only default settings but also changes to these settings...
 
How reliably can you reproduce the issue, what are the steps to do so?
can easily reproduced by renaming the default 'wallet.dat' file to custom name, adjusting that value in configuration file and then startup wallet.

What version of NavCoin Core are you using, where did you get it (website, self-compiled, etc)?
NavCoin 5.0.1 from github release repository
windows 7 64 bit

**Comment by mxaddict** [comment]
@chlorocryptos I think I fixed this issue in one of my PRs, can you try and test with behavior with latest master build?

**Comment by mxaddict** [comment]
You can download latest master build here: https://build.nav.community/binaries/master/

**Comment by mxaddict** [comment]
I tested latest master and seems this issue still exists

**Comment by chlorocryptos** [comment]
confirmed.
master behaves the same as 5.0.1 official release...

**Comment by aguycalled** [comment]
Should be fixed here https://github.com/navcoin/navcoin-core/pull/730
@chlorocryptos if you leave here a navcoin address i will send you some coins from the bug bounty for reporting this

**Comment by chlorocryptos** [comment]
nice to hear it has been fixed and i'm pleased to receive a bug bounty reward, but that hasn't been my primary objective...
nav address: NNccVpbvKfJnJ3xgbnheUtpUqhSNiBkcgP
