### ISSUE TITLE
[DAO] Combining Consensus Parameters for cfund % and rewards

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-core#737]
The current setup has these two parameters set separately. But since these two parameters are coupled, it is suggested that we somehow combine these two parameters into 1 consensus item that has two parameters so they can be changed at the same time.

For example, in the current setup, if we want to increase cfund distribution to 1 NAV per block while keeping the reward of 2 NAV per block, we will have to change the reward to 3 NAV per block at the same time increasing the percentage to 33%. In this scenario, there is no guarantee that the two consensus changes will be both approved. If only one is approved, the result would be less than ideal.

**Comment by aguycalled** [comment]
this is an interesting upgrade, which would require a bit of reengineering of how things work internally. adding a bounty and will add later some ideas on how it could be implemented

**Comment by hash512-navcoin** [comment]
How about this is defined by JSON and parsed at startup
{"reward":[{"block":0,"CFUND":0.5,"STAKE":2}]}
The above would be the initial definition based on the new scheme.  The 0 would just mean from when current staking rewards started.

It would allow a reward scheme to be built such as the below example in JSON and a maximum supply hard limit set
{"reward":[{"block":0,"CFUND":0.5,"STAKE":2},{"block":6000000,"CFUND":0.25,"STAKE":1},{"block":7000000,"CFUND":0.125,"STAKE":0.5},{"block":8000000,"CFUND":0.1,"STAKE":0.4}],"max_supply":170000000}
This would change the reward at block 6 million, 7 million and 8 million after that the reward would remain the same until the maximum supply limit of 170000000 was reached.  Obviously as that limit approached the scheme would need to be updated.  This is not how I expect the initial definition to be defined it will just be 2 stake and 0.5 community fund like it is now.

Obviously not as easy to parse JSON in C++ but can be done.  Probably some sort of web interface to parse the JSON and generate the CLI command required should be developed at the same time.

This would be a good but challenging first change for me!

**Comment by aguycalled** [comment]
first of all, what you propose is out of the topic of this issue. here OP proposed to combine two consensus parameters into one, which makes sense, as currently the approval of one of the inflation related parameters does not imply the approval of the other while both affect the inflation and normally people would vote with both on mind.

for what you propose, id suggest to gather enough support from the rest of the community before starting the work. once you think the network would approve the fork, then the change is very easy.

see `GetFundContributionPerBlock` and `GetStakingRewardPerBlock` in `main.cpp`. they would look like something like this:

```c++
uint64_t GetStakingRewardPerBlock(const CStateViewCache& view)
{
    if (!forkActive)
    {
        return GetConsensusParameter(Consensus::CONSENSUS_PARAM_GENERATION_PER_BLOCK, view) - GetFundContributionPerBlock(view);
    }
    else
    {
         if (mapBlockIndex.count(view.GetBestBlock()){
             CBlockIndex* pindex = mapBlockIndex[view.GetBestBlock()];
             if (pindex->nHeight < 1000000)
                return 2*COIN;
             else if (pindex->nHeight < 2000000)
                return 1.5*COIN;
         }
    }
}
```

Something similar for `GetFundContributionPerBlock` would be necessary.

**Comment by hash512-navcoin** [comment]
There is no fork here.  The change combines community fund and staking rewards into a single JSON defined parameter and staking reward and community fund amounts remain unchanged.

The example of the possibility that using JSON allows offering tiered reward and community fund amounts based on block is an example of what this change facilitates.  Such a change would as a minimum require a consultation before making such a change to the JSON and would result in a fork when the values change from current and not before.  But the code change to support it does not change consensus unless the JSON defining it changes.

The intention is to develop the JSON defined community fund and staking reward of {"reward":[{"block":0,"CFUND":0.5,"STAKE":2}]} which requires no fork and does not change consensus in any way.  Update code for the change of the new combined consensus parameter via DAO and update or have updated the block explorer to support it.
