### ISSUE TITLE
master.SHA256SUM.asc is not included in v5.0.1 Assets

### ISSUE THREAD

**Issue by re42** [navcoin/navcoin-core#742]
Is there a reason the file master.SHA256SUM.asc is not included in the list of Assets/Downloads?

Please can you include it for download

**Comment by mxaddict** [comment]
@re42 The hashes are in the release itself, but I think the sha sum file was not uploaded with the assets by mistake

**Comment by mxaddict** [comment]
Closing this issue now as it should not happen again in the next release.
