### ISSUE TITLE
Navcoin Core wallet crashed

### ISSUE THREAD

**Issue by francisjyap** [navcoin/navcoin-core#779]
I just noticed that navcoin-core crashed, throwing this error message:
```
navcoind: coins.cpp:857: const CTxOut& CStateViewCache::GetOutputFor(const CTxIn&) const: Assertion `coins && coins->IsAvailable(input.prevout.n)' failed.
Aborted
```

Provided below are the debug.log files from both servers.

Version: NavCoin version v6.0.0.0-2a4d0a9c-dirty
OS: Ubuntu 20.04

Debug Log Dumps:
[debug-03-02-2021.log](https://github.com/navcoin/navcoin-core/files/5918622/debug-03-02-2021.log)
[debug-03-02-2021-de.log](https://github.com/navcoin/navcoin-core/files/5918623/debug-03-02-2021-de.log)

**Comment by aguycalled** [comment]
Hi!

Would you be able to reproduce the crash running the binary together with the symbols through gdb?

The backtrace would help to debug what happened.

You'd need the dbg files from the -debug.tar.gz to be on the same folder as the binaries.

```wget https://build.nav.community/binaries/master/navcoin-6.0.0-x86_64-linux-gnu-debug.tar.gz
wget https://build.nav.community/binaries/master/navcoin-6.0.0-x86_64-linux-gnu.tar.gz
tar zxvf navcoin-6.0.0-x86_64-linux-gnu*.tar.gz
cd navcoin-6.0.0/bin
gdb navcoin-qt
```

Then `run` and `bt`  when the crash.

Please post as an answer here the output of `bt`.

**Comment by francisjyap** [comment]
Hi,

Sure, i'll try this out. I'll post the logs when it does crash again.

**Comment by chasingkirkjufell** [comment]
@francisjyap were you able to replicate the crash with gdb?

**Comment by mxaddict** [comment]
Closing, feel free to re-open if needed
