### ISSUE TITLE
4.0.4 reported size issue

### ISSUE THREAD

**Issue by colvano** [NAVCoin/navcoin-core#78]
Multiple users have been reporting scaling issues. For example on a 13" notebook screen the wallet bottom is cut off., (f.e @ProFinIn telegram) 

Perhaps a drag scaling solution as with normal windows could fix this.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T19:24:20+13:00","ped":"2017-11-22T21:51:16+13:00"})

**Comment by aguycalled** [comment]
Please, use #83 to further report about this issue.
