### ISSUE TITLE
xNAV tx history duplciated

### ISSUE THREAD

**Issue by chasingkirkjufell** [navcoin/navcoin-core#803]
This is an incoming tx. Tx history is duplicated. Swapping within the wallet shows correct history so only incoming txs are duplicated.

![image](https://user-images.githubusercontent.com/38635377/109275054-d5974000-77d9-11eb-8374-585a3cff07ea.png)

![image](https://user-images.githubusercontent.com/38635377/109275068-dc25b780-77d9-11eb-9d79-bc0c19c1428a.png)

**Comment by aguycalled** [comment]
need to check TransactionRecord::decomposeTransaction
