### ISSUE TITLE
Coin Mix count column in coin control not tracking properly.

### ISSUE THREAD

**Issue by bocyaj** [navcoin/navcoin-core#810]
I have had a bunch of xNAV inputs mixing for a few days and have noticed that the 'Mix Count' column in the coin control window is not properly tracking the number of times an input has been mixed.

I am running Windows 10 64-bit wallet version 6.0.2.

![image](https://user-images.githubusercontent.com/19207801/109709273-4b98ff80-7b6a-11eb-8f9d-7f12a767e7e6.png)

I always transfer round number amounts when moving coins over to xNAV, and they have not moved since.

So you can see the number of rewards each input has recieved compared to the mixing count.

I believe the values have been updating over time, but it has always been either 1 or 0.

I will keep closer track on the counts and see what changes happen after each mixing session.  
Will provide updates if I find out more.

Thanks.

**Comment by bocyaj** [comment]
Coin mix count seems to be working properly now.  I suspect either repairing wallet or restoring from mnemonic phrase resets the counters.
Will confirm when i get a chance.

**Comment by bocyaj** [comment]
I confirmed coin-mix count is restored correctly after importing wallet using mnemonic phrase.

**Comment by aguycalled** [comment]
closing. reopen if issue still exists
