### ISSUE TITLE
unable to resize wallet in Windows 10 x64

### ISSUE THREAD

**Issue by bocyaj** [NAVCoin/navcoin-core#82]
Not sure if this is intended or was needed to implement 4k support, but I can no longer resize the wallet window in NAV Coin Core v4.0.4.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T21:51:16+13:00","ped":"2017-11-23T00:18:12+13:00"})

**Comment by aguycalled** [comment]
Please, use #83 to further report about this issue.
