### ISSUE TITLE
gpg sig for navcoin-6.0.2-x86_64-linux-gnu.tar.gz?

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [navcoin/navcoin-core#825]
I suggest that the sha256sums on this page
https://github.com/NAVCoin/navcoin-core/releases/tag/6.0.2
be labeled "sha256sums" instead of just "hashes". I see nothing like a gpg signature for the hashes or navcoin-6.0.2-x86_64-linux-gnu.tar.gz. I'd feel a lot better about it if it were signed with a signature that could be verified with multiple public keyservers.

**Comment by aguycalled** [comment]
you can find signatures for the different gitian builds for each commit here:

https://build.nav.community/binaries/master/gitian.sigs/

signed with https://keys.openpgp.org/vks/v1/by-fingerprint/1BF9B51BAED51BA0B3A174EE2782262BF6E7FADB (builder@nav.community)
