### ISSUE TITLE
TestNet not syncing

### ISSUE THREAD

**Issue by mxaddict** [NAVCoin/navcoin-core#84]
TestNet not syncing:

I installed navcoin-core 4.x on a VPS and on my local development PC and can't get the navcoind daemon to sync with the testnet.

I ran with the following command
```bash
navcoind -testnet
```

I get this response from navcoin-cli:
```bash
# navcoin-cli -testnet getpeerinfo
[
  {
    "id": 13,
    "addr": "95.183.52.28:44444",
    "services": "0000000000000000",
    "relaytxes": false,
    "lastsend": 1504566393,
    "lastrecv": 0,
    "bytessent": 125,
    "bytesrecv": 0,
    "conntime": 1504566393,
    "timeoffset": 0,
    "version": 0,
    "subver": "",
    "inbound": false,
    "startingheight": -1,
    "banscore": 0,
    "synced_headers": -1,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "version": 125
    },
    "bytesrecv_per_msg": {
    }
  }
]
```

And sometimes there are no peers at all.

So question is, do you have a testnet NODE that I can add as a peer to sync from? thank

**Comment by aguycalled** [comment]
please use branch v4.1.0 to connect to the testnet. i can send you some test coins if you give me your address.
