### ISSUE TITLE
Navcoin Core Wallet - Error Reading from Database, Shutting Down

### ISSUE THREAD

**Issue by yraen69** [navcoin/navcoin-core#848]
Open wallet, starts syncing chain. Crashes with "Error Reading from Database, Shutting Down"

Wallet to open and sync.

![image](https://user-images.githubusercontent.com/17959135/121764735-a930e500-cb78-11eb-8af3-ff84fa289bfc.png)

Every time I open the wallet.

6.1.0.0 from official website

Windows 10, Ryzen 3800XT, SSD disk

Debug Log

2021-06-12 04:12:25 Peer=30 is stalling block download, disconnecting
...
2021-06-12 04:13:10 UpdateTip: new best=7ded1a885bed22ddc8d0889b1c5cb3fd2a9a9f583559102fc82ee538388865ec height=5265145 version=0x7bf5f5ff log2_work=73.698221 tx=10948967 date='2021-06-08 07:20:16' progress=0.996087 cache=6.3MiB(14859tx)
2021-06-12 04:13:10 UpdateTip: new best=1fcc2c8be9ceca4ba300f5406d42657d973fb435bae8bd924fe60e3c10561ed1 height=5265146 version=0x7bf5f5ff log2_work=73.698221 tx=10948969 date='2021-06-08 07:21:52' progress=0.996088 cache=6.3MiB(14861tx)
2021-06-12 04:13:10 LevelDB read failure: Corruption: block checksum mismatch: C:\Users\Luke\AppData\Roaming\NavCoin4\chainstate/010867.ldb
2021-06-12 04:13:10 Corruption: block checksum mismatch: C:\Users\USER\AppData\Roaming\NavCoin4\chainstate/010867.ldb
2021-06-12 04:13:20 INFO: Updating prices
2021-06-12 04:13:20 INFO: Updated prices

**What would I like to see from this ticket?**

A wallet UI enhancement. I suspect this is a corrupt DB and there is some esoteric cmd line I can run to fix it or rebuilt it. It's 2021 if we want adoption we shouldn't be forcing people to do that. Put a button on the error popup that says 'Repair' and try and fix this automatically for people. Obviously you can't fix everything and the fallback after that can be said cmd line fix.

Thanks all!

**Comment by yraen69** [comment]
Just FYI as well, I can't get to the FILE -- Repair option suggested here https://info.navcoin.org/navcoin-core/repair-your-wallet/ as the wallet crashes basically as soon as the sync progress screen appears.

**Comment by yraen69** [comment]
So I managed to get to File --> Repair wallet... had to load up my CPU's with a stress test at 100% load so the entire machine was running slowly... gave me just enough time to get to the repair option before the wallet crashed. Popped up the OK message to start repairing and off it went... issue fixed. Still not a great user experience.

**Comment by aguycalled** [comment]
from the error log you attach, your issue was a corruption of the chainstate db. this is fixed with a resync/bootstrap

repairing the wallet has nothing to do with the issue you comment. i can’t see the connection

**Comment by yraen69** [comment]
Hi aguycalled,

thought my experience was pretty clear, end user wise it wasn't great. Yes it was a chain corruption issue. If you look at my screenshot the error box pops up within a couple of seconds of the wallet finally loading. All you can do is click OK and the wallet crashes. 

This is BAD. You cannot get to FILE --> Repair Wallet. 

I had to load up all of my CPU cores to make my machine run SLOW enough for me to have enough time to get to the FILE --> Repair option and click that before the error message pops up crashing my wallet. This is a stupid design. 

That 'Error reading from database shutting down' message should NOT be a fatal one that instantly closes the wallet and gives you not option but to click OK. 

It should instead actually give you the option to repair the wallet ON that error popup or at least grey out the main UI and let you at least click FILE --> Repair wallet.

**Comment by aguycalled** [comment]
i understand what you mean, but that would not be a valid solution for issues like yours. clicking repair wallet was not what solved your database corruption, as wallet repair only manipulates walelt.dat while in your case it was the chainstate/* databases what was corrupted

chainstate corruption is only solved by resyncing/reindexing/bootstrapping

**Comment by yraen69** [comment]
Hi aguycalled,

sure do whatever you like with this ticket. My fix was to click File --> Repair Wallet. That's all I did and about an hour later my wallet worked again. 

I stand by my recommendation, that error should not be fatal in my original screenshot it should instead prompt you to repair whatever is broken, I don't particularly care if it's the wallet or the chain, as an end user I shouldn't have to care. 

The wallet should be very very difficult to get into an unworkable state that just crashes and crashes if you want to build adoption.

regards
Luke

**Comment by aguycalled** [comment]
i agree with you about the importance of improving user experience. 

From my point of view the solution is more about educating users who are non-tech savvy in using light wallets instead of running full nodes. A full node will always require technical maintenance - someone who is not skilled enough to run a full node will eventually feel disappointed and have a bad experience, and this not only applies to Navcoin. Our problem is that we offer Navcoin Core as the wallet de facto, so it's the option most of the users choose.

This is something we are currently working to solve, by upgrading our website to adequate the narrative by explaining well what each wallet is used better for and showing light wallets as the first choice; by adding to our light wallets some of the functionality that is currently missing (like xNAV private transactions); and with the release of NavcoinJS, a SDK for developers to easily build wallets on top of our network.

This is our focus currently. I personally think adding extra layers of complication to Navcoin Core's code in sake of automating the solution of some issues won't be as benefitial for the project, the performance of our wallets and the experience of our users as what I aforementioned.

**Comment by yraen69** [comment]
Thank you for your concise and excellent feedback, I'm glad to see the future direction and what's being worked on for light wallets. Agree it's the future. Your time is appreciated! Long time NAV supporter myself, I think it's got a great future. 

Given what you've said here I'll close this issue and look forward to what's coming up in the future!
