### ISSUE TITLE
"getbalance" RPC method only shows public balance

### ISSUE THREAD

**Issue by sakdeniz** [navcoin/navcoin-core#853]
I sent xNAV to a newly created wallet. However, I noticed that when I call the "getbalance" RPC method, it only shows the public balance.

An update can be made to display balances under 3 different headings such as Public balance, Private balance and Total balance.

**Comment by mxaddict** [comment]
@sakdeniz I think `getbalance` is deprecated and should be removed in the future, maybe use `getwalletinfo` instead?

**Comment by mxaddict** [comment]
Closing for now since `getbalance` RPC is deprecated
