### ISSUE TITLE
[Linux] v4.0.5 resolution problem 

### ISSUE THREAD

**Issue by dmitrime** [NAVCoin/navcoin-core#87]
Version 4.0.5 window looks too big on linux laptop running with resolution 1920x1080. There is no option to maximize the window or resize it to smaller size. It's so big that the status message ("Connected to NavCoin network...") at the bottom is not visible.

- - -
[Elegantt data. What's this?](http://bit.ly/elegantt-for-trello-whats-this)
[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-23T02:45:09+13:00","ped":"2017-11-23T05:12:05+13:00"})

**Comment by aguycalled** [comment]
Please, use #83 to further report about this issue.
