### ISSUE TITLE
Import wallet button

### ISSUE THREAD

**Issue by colvano** [navcoin/navcoin-core#90]
Under _file_ the user can _backup wallet_. It would be nice if there was a button _import wallet_.

This would warn the user of the effect, ask the user to make a backup first, select wallet to import, close wallet, and restart wallet with the imported wallet.

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T03:16:15+13:00","ped":"2017-11-22T06:48:01+13:00"})

**Comment by mxaddict** [comment]
We have mnemonic support now, not sure if we want this still.

**Comment by mxaddict** [comment]
@aguycalled @proletesseract @chasingkirkjufell 

Think this is still needed for the wallet?

**Comment by mxaddict** [comment]
I think we can close this now that we have mnemonic key support
