### ISSUE TITLE
Balance display problem after getting staking reward.

### ISSUE THREAD

**Issue by Nihche** [navcoin/navcoin-core#909]
After getting the stake reward, last transaction + some of stake reward shows under Immature and it stays like that(even after 11 hours) until i reset the core wallet. 

Before staking reward(i photoshoped balance numbers for privacy reasons):
![navb](https://user-images.githubusercontent.com/97336295/148640082-743ff9b3-1653-4546-a613-42806173baf7.PNG)
After staking reward:
![navc](https://user-images.githubusercontent.com/97336295/148640086-3ec1eef0-4eb0-453c-88fb-a9588141db76.PNG)

This happened for every stake i got so far. And i needed to reset core wallet to set to correct balance. This first time it sent 500NAV to immature which was first deposit, and now it sends 1000NAV to immature which was later deposit.

Happened on both linux and windows, 2 different PCs.
On linux i was using 7.0.0 and on windows i have 7.0.1 versions of core wallet.

**Comment by mxaddict** [comment]
We have seen this issue before, its related to cache values of the balance
displayed.

I'm still working on a fix for this issue.

**Comment by mxaddict** [comment]
#917 fixes this issue and is now merged into master branch
