### ISSUE TITLE
Wallet giving error on opening in OSX

### ISSUE THREAD

**Issue by Tissuelion** [NAVCoin/navcoin-core#93]
Hi, I was using navwallet version 4.0.4 running on OSX 10.11.5. A few days ago the wallet crashed and when I try to start it, I get the error "Error: A fatal internal error occurred, see debug.log for details" and then the software closes again. I don't see any debug.log file when I open the package contents or when I search my computer (I've set my system to display hidden files as well). I also installed wallet 4.0.5 and I get the same error.

Curious if anyone has run into this before? I made a few backups of my wallet so I'm assuming I should delete then reinstall, but I wanted to check on here first.

Thanks for any help!

**Comment by ltyu** [comment]
+1 also having this issue

**Comment by doreido41** [comment]
I'm also having this same issue with OSX - has anyone found a fix?

**Comment by Tissuelion** [comment]
Hey - was able to figure out a fix to this last night on my own actually. I went to my harddrive -> Users -> [computer name] -> Library (make sure hidden files are visible to see this) -> Application Support -> Navcoin4.

From there, copy and paste the wallet.dat folder to your desktop or somewhere else. DO NOT let this file get deleted because it seems to be the key to recovering access to your coins.

Once wallet.dat is safe, delete the Navcoin4 folder and delete the app from the Applications folder. Download the newest wallet, reinstall. Open the application and select the create new wallet option and let it run for a few minutes. Then close it. Go back to the Navcoin4 folder as above, and copy and paste your old "wallet.dat" file into there, overwriting the new one that's been installed. Again make sure that you don't cut & paste the old wallet file, you want to have a copy of this elsewhere just in case the backup doesn't work.

Then open the Nav application again and it should start synching the blockchain from scratch. In my case it showed me the transactions I had done but it didn't show the coins in the wallet until it reached the blocks they were processed in.

Good luck!

**Comment by doreido41** [comment]
Hey Tissuelion - Thanks so much for taking the time to type all this out!
I'm excited to give it a go later tonight when I get home

Thanks!

**Comment by ltyu** [comment]
I also followed @Tissuelion recommendation to resync the blockchain. That was the only solution that works. Luckily the Nav blockchain isn't huge so it didn't take too long
