### ISSUE TITLE
Running own node: Waiting for the node to be ready...

### ISSUE THREAD

**Issue by MikeW83** [navcoin/navcoin-core#942]
Hello guys!

I have a problem. There iare so many guides but nothing which is really up to date. I want to run a node without cold staking. I have installed everything on Ubuntu 20.04 with the script from https://doc.nav.community/get.html without Electrum.
I think it's correct until this. But now it's always saying "Waiting for the node to be ready" since hours.

What I'm doing wrong. When the node is running I want to use my wallet where all my coins are stored for staking. Where can I get all needed information for running this in an appropriate way?

Thank you very much.

Best regards, Michael

**Comment by mxaddict** [comment]
Is the node syncing with the network?

**Comment by MikeW83** [comment]
yes... I have tried to use navcoin-cli from source directory because elsewhere there was nothing to find. I have entered my passphrase for my wallet and activated staking and it's working... In the meantime I have rebootet the server because there was nothing to find.
And within the debug.log there where always listed actual blocks.

**Comment by aguycalled** [comment]
what do you see above Waiting for the node to be ready.. ?

You should have something descriptive like this:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/24814046/159019902-8212ebff-5f45-4ad3-9813-c78ad8ea97c0.png">

**Comment by aguycalled** [comment]
There is an alias created on `.bashrc` so you should be able to use just `navcoin-cli`

**Comment by MikeW83** [comment]
> 

Yes, and then it continues with "Waiting for the node to be ready..." And nothing happens.

**Comment by MikeW83** [comment]
> There is an alias created on `.bashrc` so you should be able to use just `navcoin-cli`

No is not. I think the link is created when the script completes. But it has never completed. Starting and stopping the server is working with systemctl.

**Comment by aguycalled** [comment]
> Yes, and then it continues with "Waiting for the node to be ready..." And nothing happens.

Trying it myself now to see if there is a bug detecting if the daemon init completed.

**Comment by aguycalled** [comment]
Patched some bugs on the script. Could you try it again? @MikeW83

**Comment by MikeW83** [comment]
> Patched some bugs on the script. Could you try it again? @MikeW83

Sure, I will give it a try.

**Comment by MikeW83** [comment]
I stopped navcoind.service and ran the script like I've done before from the URL in the documentation. Also without Electrum.

and this is the debug.log

> 2022-03-18 21:34:54 Navcoin version v7.0.2.0-c11deddd
> 2022-03-18 21:34:54 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
> 2022-03-18 21:34:55 Default data directory /home/navcoin/.navcoin4
> 2022-03-18 21:34:55 Using data directory /var/lib/navcoind
> 2022-03-18 21:34:55 Using config file /etc/navcoin/navcoin.conf
> 2022-03-18 21:34:55 Using at most 125 connections (1024 file descriptors available)
> 2022-03-18 21:34:55 Using 2 threads for script verification
> 2022-03-18 21:34:55 scheduler thread start
> 2022-03-18 21:34:55 HTTP: creating work queue of depth 16
> 2022-03-18 21:34:55 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
> 2022-03-18 21:34:55 HTTP: starting 4 worker threads
> 2022-03-18 21:34:55 Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
> 2022-03-18 21:34:55 Using wallet wallet.dat
> 2022-03-18 21:34:55 init message: Verifying wallet...
> 2022-03-18 21:34:55 CDBEnv::Open: LogDir=/var/lib/navcoind/database ErrorFile=/var/lib/navcoind/db.log
> 2022-03-18 21:34:55 init message: Synchronizing clock...
> 2022-03-18 21:34:55 [NTP] Starting clock sync...
> 2022-03-18 21:35:01 [NTP] Measured: au.pool.ntp.org[0sec.] nl.pool.ntp.org[0sec.] br.pool.ntp.org[0sec.] 0.de.pool.ntp.org[0sec.] rustime01.rus.uni-stuttgart.de[0sec.]
> 2022-03-18 21:35:01 [NTP] Calculated offset from median: 0
> 2022-03-18 21:35:01 Bound to [::]:44440
> 2022-03-18 21:35:01 Bound to 0.0.0.0:44440
> 2022-03-18 21:35:01 Block index database configuration:
> 2022-03-18 21:35:01 * Using 1000 max open files
> 2022-03-18 21:35:01 * Compression is enabled
> 2022-03-18 21:35:01 Cache configuration:
> 2022-03-18 21:35:01 * Using 2.0MiB for block index database
> 2022-03-18 21:35:01 * Using 56.0MiB for transaction index database
> 2022-03-18 21:35:01 * Using 8.0MiB for chain state database
> 2022-03-18 21:35:01 * Using 384.0MiB for in-memory UTXO set (plus up to 47.7MiB of unused mempool space)
> 2022-03-18 21:35:01 init message: Loading block index...
> 2022-03-18 21:35:01 Opening LevelDB in /var/lib/navcoind/blocks/index
> 2022-03-18 21:35:09 Opened LevelDB successfully
> 2022-03-18 21:35:09 Using obfuscation key for /var/lib/navcoind/blocks/index: 0000000000000000
> 2022-03-18 21:35:09 Opening LevelDB in /var/lib/navcoind/chainstate
> 2022-03-18 21:35:25 Opened LevelDB successfully
> 2022-03-18 21:35:25 Using obfuscation key for /var/lib/navcoind/chainstate: f77a7912efdf1bc2
> 2022-03-18 21:35:25 init message: Loading block guts...
> 2022-03-18 21:40:29 init message: Loading block index...
> 2022-03-18 21:42:45

and after that the service restarted and then again:

> 2022-03-18 21:42:45 Navcoin version v7.0.2.0-c11deddd
> 2022-03-18 21:42:45 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
> 2022-03-18 21:42:46 Default data directory /home/navcoin/.navcoin4
> 2022-03-18 21:42:46 Using data directory /var/lib/navcoind
> 2022-03-18 21:42:46 Using config file /etc/navcoin/navcoin.conf
> 2022-03-18 21:42:46 Using at most 125 connections (1024 file descriptors available)
> 2022-03-18 21:42:46 Using 2 threads for script verification
> 2022-03-18 21:42:46 scheduler thread start
> 2022-03-18 21:42:46 HTTP: creating work queue of depth 16
> 2022-03-18 21:42:46 Config options rpcuser and rpcpassword will soon be deprecated. Locally-run instances may remove rpcuser to use cookie-based auth, or may be replaced with rpcauth. Please see share/rpcuser for rpcauth auth generation.
> 2022-03-18 21:42:46 HTTP: starting 4 worker threads
> 2022-03-18 21:42:46 Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)
> 2022-03-18 21:42:46 Using wallet wallet.dat
> 2022-03-18 21:42:46 init message: Verifying wallet...
> 2022-03-18 21:42:46 CDBEnv::Open: LogDir=/var/lib/navcoind/database ErrorFile=/var/lib/navcoind/db.log
> 2022-03-18 21:42:46 init message: Synchronizing clock...
> 2022-03-18 21:42:46 [NTP] Starting clock sync...
> 2022-03-18 21:43:12 [NTP] Measured: time4.google.com[0sec.] time2.google.com[0sec.] 0.de.pool.ntp.org[0sec.] cuco.rediris.es[0sec.] hora.roa.es[0sec.]
> 2022-03-18 21:43:12 [NTP] Calculated offset from median: 0
> 2022-03-18 21:43:12 Bound to [::]:44440
> 2022-03-18 21:43:12 Bound to 0.0.0.0:44440
> 2022-03-18 21:43:12 Block index database configuration:
> 2022-03-18 21:43:12 * Using 1000 max open files
> 2022-03-18 21:43:12 * Compression is enabled
> 2022-03-18 21:43:12 Cache configuration:
> 2022-03-18 21:43:12 * Using 2.0MiB for block index database
> 2022-03-18 21:43:12 * Using 56.0MiB for transaction index database
> 2022-03-18 21:43:12 * Using 8.0MiB for chain state database
> 2022-03-18 21:43:12 * Using 384.0MiB for in-memory UTXO set (plus up to 47.7MiB of unused mempool space)
> 2022-03-18 21:43:12 init message: Loading block index...
> 2022-03-18 21:43:12 Opening LevelDB in /var/lib/navcoind/blocks/index
> 2022-03-18 21:43:12 Opened LevelDB successfully
> 2022-03-18 21:43:12 Using obfuscation key for /var/lib/navcoind/blocks/index: 0000000000000000
> 2022-03-18 21:43:12 Opening LevelDB in /var/lib/navcoind/chainstate
> 2022-03-18 21:43:12 Opened LevelDB successfully
> 2022-03-18 21:43:12 Using obfuscation key for /var/lib/navcoind/chainstate: f77a7912efdf1bc2
> 2022-03-18 21:43:12 init message: Loading block guts...

and now it keeps showing this in console:

![image](https://user-images.githubusercontent.com/35097389/159088361-5eda1048-e0cb-4b5a-92d2-730051493020.png)

**Comment by MikeW83** [comment]
I have deleted the directories chainstate, blocks and database and then script has finished.

**Comment by aguycalled** [comment]
so is it all working now? should I close the issue?

**Comment by MikeW83** [comment]
Hello. Yes, now it's working. Thank you.
