### ISSUE TITLE
Are your downloads not supposed to be signed?

### ISSUE THREAD

**Issue by 2SI3NX** [NAVCoin/navcoin-core#98]
Just wondering if its best to sign your packages so the user can verify using sigs as well?

[](Elegantt!UNITO-UNDERSCORE!data:dont!UNITO-UNDERSCORE!delete{"ignored":false,"autoPlanned":true,"ownerId":false,"dependencies":[],"psd":"2017-11-22T06:23:08+13:00","ped":"2017-11-22T08:59:39+13:00"})

**Comment by 2SI3NX** [comment]
Would anyone care to reply? Seeing the NAV team not responding much on github issues is very concerning.

**Comment by aguycalled** [comment]
binaries are not currently signed. i agree it would be good to do it

**Comment by 2SI3NX** [comment]
thank you. hope that happens soon
